In [102]:
print("hello")

hello

In [103]:
import pandas as pd
import numpy as np
import re
print(pd.__version__)

2.3.3

In [104]:
import sys
print(sys.executable)

/home/rifat/Documents/feastAI/appenv/bin/python

In [105]:
data = pd.read_csv("rawData.csv", encoding='utf-8')

In [106]:
print(data.head())

      Area                   Restaurant Name  Rating (List View)  \
0  gulshan          Chef's Table - Gulshan 2                 4.5
1  gulshan  The New Gulshan Plaza Restaurant                 4.2
2  gulshan                   Seasonal Tastes                 4.6
3  gulshan      Sultan's Dine Gulshan Branch                 4.3
4  gulshan     HEXA Dine - Restaurant & Café                 4.2

  Number of Reviews (List View)  Location Coordinates (Latitude)  \
0                         9,895                        23.795731
1                         4,042                        23.793650
2                         1,469                        23.793366
3                        11,475                        23.794849
4                           740                        23.791929

   Location Coordinates (Longitude)  \
0                         90.414948
1                         90.414331
2                         90.414648
3                         90.413267
4                         90.406217

                                  Location (Address) Contact Info (Phone)  \
0                   Gulshan Centre Point, Dhaka 1212         01918-643663
1                               33 Rd 45, Dhaka 1212         01850-509001
2           The Westin, Main Gulshan Ave, Dhaka 1212         01730-304871
3  1st floor, Samsuddin Mansion, House: 41 Road: ...                  NaN
4  House: 34 (1st Floor), Green Regency, Road No:...         01886-439222

                      Price Range (Per Person)  \
0                                          NaN
1  ৳200–400 per person\nReported by 264 people
2                                          NaN
3  ৳400–600 per person\nReported by 864 people
4                                          NaN

  Operation Days and Time (Full Schedule) Accessibility  Service Options  \
0          N/A - Data Collection Disabled           NaN              NaN
1          N/A - Data Collection Disabled           NaN              NaN
2          N/A - Data Collection Disabled           NaN              NaN
3          N/A - Data Collection Disabled           NaN              NaN
4          N/A - Data Collection Disabled           NaN              NaN

   Highlights Meal Type (From Sample Review 1)  \
0         NaN                            Lunch
1         NaN                            Lunch
2         NaN                              NaN
3         NaN                           Dinner
4         NaN                            Lunch

  Price Per Person (From Sample Review 1)  \
0                                ৳600–800
1                                ৳200–400
2                                     NaN
3                                 ৳2,000+
4                                 ৳2,000+

                                            Maps URL  \
0  https://www.google.ca/maps/place/Chef%27s+Tabl...
1  https://www.google.ca/maps/place/The+New+Gulsh...
2  https://www.google.ca/maps/place/Seasonal+Tast...
3  https://www.google.ca/maps/place/Sultan%27s+Di...
4  https://www.google.ca/maps/place/HEXA+Dine+-+R...

                                 Sample User Reviews
0  Review 1 (4 stars): Clean food court. There ar...
1  Review 1 (4 stars): Apart from the very busy a...
2  Review 1 (5 stars): Top notch display 🤯🤯one of...
3  Review 1 (5 stars): Sultan's Dine in Gulshan i...
4  Review 1 (5 stars): This is my first time visi...

In [107]:
print(data.columns)

Index(['Area', 'Restaurant Name', 'Rating (List View)',
       'Number of Reviews (List View)', 'Location Coordinates (Latitude)',
       'Location Coordinates (Longitude)', 'Location (Address)',
       'Contact Info (Phone)', 'Price Range (Per Person)',
       'Operation Days and Time (Full Schedule)', 'Accessibility',
       'Service Options', 'Highlights', 'Meal Type (From Sample Review 1)',
       'Price Per Person (From Sample Review 1)', 'Maps URL',
       'Sample User Reviews'],
      dtype='object')

In [108]:
data.dtypes

Area                                        object
Restaurant Name                             object
Rating (List View)                         float64
Number of Reviews (List View)               object
Location Coordinates (Latitude)            float64
Location Coordinates (Longitude)           float64
Location (Address)                          object
Contact Info (Phone)                        object
Price Range (Per Person)                    object
Operation Days and Time (Full Schedule)     object
Accessibility                               object
Service Options                            float64
Highlights                                 float64
Meal Type (From Sample Review 1)            object
Price Per Person (From Sample Review 1)     object
Maps URL                                    object
Sample User Reviews                         object
dtype: object

In [109]:
data.columns

Index(['Area', 'Restaurant Name', 'Rating (List View)',
       'Number of Reviews (List View)', 'Location Coordinates (Latitude)',
       'Location Coordinates (Longitude)', 'Location (Address)',
       'Contact Info (Phone)', 'Price Range (Per Person)',
       'Operation Days and Time (Full Schedule)', 'Accessibility',
       'Service Options', 'Highlights', 'Meal Type (From Sample Review 1)',
       'Price Per Person (From Sample Review 1)', 'Maps URL',
       'Sample User Reviews'],
      dtype='object')

In [110]:
data.rename(columns={
    'Restaurant Name': 'name',
    'Rating (List View)': 'rating',
    'Number of Reviews (List View)': 'reviews_count',
    'Location Coordinates (Latitude)': 'latitude',
    'Location Coordinates (Longitude)': 'longitude',
    'Location (Address)': 'address',
    'Contact Info (Phone)': 'contact',
    'Price Range (Per Person)': 'price_range',
    'Price Per Person (From Sample Review 1)': 'price_per_person',
    'Maps URL': 'map_url',
    'Sample User Reviews': 'sample_user_reviews'
}, inplace=True)

In [111]:
data.drop(columns=['Area', 'Meal Type (From Sample Review 1)', 'Accessibility', 'Service Options', 'Highlights', 'Operation Days and Time (Full Schedule)'], inplace=True)

In [112]:
data.columns

Index(['name', 'rating', 'reviews_count', 'latitude', 'longitude', 'address',
       'contact', 'price_range', 'price_per_person', 'map_url',
       'sample_user_reviews'],
      dtype='object')

In [113]:
print(data.head())

                               name  rating reviews_count   latitude  \
0          Chef's Table - Gulshan 2     4.5         9,895  23.795731
1  The New Gulshan Plaza Restaurant     4.2         4,042  23.793650
2                   Seasonal Tastes     4.6         1,469  23.793366
3      Sultan's Dine Gulshan Branch     4.3        11,475  23.794849
4     HEXA Dine - Restaurant & Café     4.2           740  23.791929

   longitude                                            address       contact  \
0  90.414948                   Gulshan Centre Point, Dhaka 1212  01918-643663
1  90.414331                               33 Rd 45, Dhaka 1212  01850-509001
2  90.414648           The Westin, Main Gulshan Ave, Dhaka 1212  01730-304871
3  90.413267  1st floor, Samsuddin Mansion, House: 41 Road: ...           NaN
4  90.406217  House: 34 (1st Floor), Green Regency, Road No:...  01886-439222

                                   price_range price_per_person  \
0                                          NaN         ৳600–800
1  ৳200–400 per person\nReported by 264 people         ৳200–400
2                                          NaN              NaN
3  ৳400–600 per person\nReported by 864 people          ৳2,000+
4                                          NaN          ৳2,000+

                                             map_url  \
0  https://www.google.ca/maps/place/Chef%27s+Tabl...
1  https://www.google.ca/maps/place/The+New+Gulsh...
2  https://www.google.ca/maps/place/Seasonal+Tast...
3  https://www.google.ca/maps/place/Sultan%27s+Di...
4  https://www.google.ca/maps/place/HEXA+Dine+-+R...

                                 sample_user_reviews
0  Review 1 (4 stars): Clean food court. There ar...
1  Review 1 (4 stars): Apart from the very busy a...
2  Review 1 (5 stars): Top notch display 🤯🤯one of...
3  Review 1 (5 stars): Sultan's Dine in Gulshan i...
4  Review 1 (5 stars): This is my first time visi...

In [114]:
print(data['price_range'].isnull().sum())

261

In [115]:
print(data['price_per_person'].isnull().sum())

177

In [116]:
print(data[['rating', 'price_per_person']].head(100))

    rating price_per_person
0      4.5         ৳600–800
1      4.2         ৳200–400
2      4.6              NaN
3      4.3          ৳2,000+
4      4.2          ৳2,000+
..     ...              ...
95     4.4         ৳400–600
96     4.8          ৳2,000+
97     4.3     ৳1,000–1,200
98     4.3              NaN
99     4.2     ৳1,000–1,200

[100 rows x 2 columns]

In [117]:
data['price_per_person'] = data['price_per_person'].str.replace('৳', '').str.replace(',', '').str.strip()

print(data[['price_per_person']].head(100))

   price_per_person
0           600–800
1           200–400
2               NaN
3             2000+
4             2000+
..              ...
95          400–600
96            2000+
97        1000–1200
98              NaN
99        1000–1200

[100 rows x 1 columns]

In [118]:
print(data[['rating', 'price_per_person']].head(50))

    rating price_per_person
0      4.5          600–800
1      4.2          200–400
2      4.6              NaN
3      4.3            2000+
4      4.2            2000+
5      4.5              NaN
6      4.4              NaN
7      4.2          600–800
8      4.0        1400–1600
9      4.0        1000–1200
10     4.4        1600–1800
11     4.6            2000+
12     4.5          400–600
13     4.4              NaN
14     4.2        1200–1400
15     4.4            2000+
16     4.3        1200–1400
17     4.3        1800–2000
18     4.3          400–600
19     4.4              NaN
20     4.8        1200–1400
21     4.0        1600–1800
22     4.2         800–1000
23     4.3              NaN
24     4.4              NaN
25     4.5         800–1000
26     4.5        1400–1600
27     4.2          600–800
28     4.4          200–400
29     4.0              NaN
30     4.5            2000+
31     4.2          200–400
32     4.2          400–600
33     4.0          400–600
34     4.1          600–800
35     4.4            2000+
36     4.1         800–1000
37     4.3              NaN
38     4.5            2000+
39     4.2        1200–1400
40     4.4            2000+
41     4.3            2000+
42     4.1            2000+
43     4.1        1400–1600
44     4.2          600–800
45     4.2              NaN
46     4.5         800–1000
47     4.3              NaN
48     4.4        1800–2000
49     4.2            2000+

In [119]:
def convert_range_to_mean(value):
    if pd.isna(value):
        return value
    elif '–' in str(value):  
        start, end = map(int, value.split('–'))
        return int((start + end) / 2) 
    elif '+' in str(value):  
        return int(value.replace('+', ''))  
    return value

data['price_per_person'] = data['price_per_person'].apply(convert_range_to_mean)

print(data[['rating', 'price_per_person']].head(50))

    rating  price_per_person
0      4.5             700.0
1      4.2             300.0
2      4.6               NaN
3      4.3            2000.0
4      4.2            2000.0
5      4.5               NaN
6      4.4               NaN
7      4.2             700.0
8      4.0            1500.0
9      4.0            1100.0
10     4.4            1700.0
11     4.6            2000.0
12     4.5             500.0
13     4.4               NaN
14     4.2            1300.0
15     4.4            2000.0
16     4.3            1300.0
17     4.3            1900.0
18     4.3             500.0
19     4.4               NaN
20     4.8            1300.0
21     4.0            1700.0
22     4.2             900.0
23     4.3               NaN
24     4.4               NaN
25     4.5             900.0
26     4.5            1500.0
27     4.2             700.0
28     4.4             300.0
29     4.0               NaN
30     4.5            2000.0
31     4.2             300.0
32     4.2             500.0
33     4.0             500.0
34     4.1             700.0
35     4.4            2000.0
36     4.1             900.0
37     4.3               NaN
38     4.5            2000.0
39     4.2            1300.0
40     4.4            2000.0
41     4.3            2000.0
42     4.1            2000.0
43     4.1            1500.0
44     4.2             700.0
45     4.2               NaN
46     4.5             900.0
47     4.3               NaN
48     4.4            1900.0
49     4.2            2000.0

In [120]:
def replace_nan_based_on_rating(row):
    if pd.isna(row['price_per_person']):
        if row['rating'] >= 4.6:
            return 1000
        elif row['rating'] >= 4.5:
            return 750
        elif row['rating'] >= 4.2:
            return 650
        else:
            return 450
    return row['price_per_person']

data['price_per_person'] = data.apply(replace_nan_based_on_rating, axis=1)

print(data[['rating', 'price_per_person']].head(50))

    rating  price_per_person
0      4.5             700.0
1      4.2             300.0
2      4.6            1000.0
3      4.3            2000.0
4      4.2            2000.0
5      4.5             750.0
6      4.4             650.0
7      4.2             700.0
8      4.0            1500.0
9      4.0            1100.0
10     4.4            1700.0
11     4.6            2000.0
12     4.5             500.0
13     4.4             650.0
14     4.2            1300.0
15     4.4            2000.0
16     4.3            1300.0
17     4.3            1900.0
18     4.3             500.0
19     4.4             650.0
20     4.8            1300.0
21     4.0            1700.0
22     4.2             900.0
23     4.3             650.0
24     4.4             650.0
25     4.5             900.0
26     4.5            1500.0
27     4.2             700.0
28     4.4             300.0
29     4.0             450.0
30     4.5            2000.0
31     4.2             300.0
32     4.2             500.0
33     4.0             500.0
34     4.1             700.0
35     4.4            2000.0
36     4.1             900.0
37     4.3             650.0
38     4.5            2000.0
39     4.2            1300.0
40     4.4            2000.0
41     4.3            2000.0
42     4.1            2000.0
43     4.1            1500.0
44     4.2             700.0
45     4.2             650.0
46     4.5             900.0
47     4.3             650.0
48     4.4            1900.0
49     4.2            2000.0

In [121]:
data.isnull().sum()

name                     0
rating                   0
reviews_count            0
latitude                 0
longitude                0
address                  1
contact                 65
price_range            261
price_per_person         0
map_url                  0
sample_user_reviews      1
dtype: int64

In [122]:
data.head()

,name,rating,reviews_count,latitude,longitude,address,contact,price_range,price_per_person,map_url,sample_user_reviews
0,Chef's Table - Gulshan 2,4.5,"9,895",23.795731,90.414948,"Gulshan Centre Point, Dhaka 1212",01918-643663,NaN,700.0,https://www.google.ca/maps/place/Chef%27s+Tabl...,Review 1 (4 stars): Clean food court. There ar...
1,The New Gulshan Plaza Restaurant,4.2,"4,042",23.793650,90.414331,"33 Rd 45, Dhaka 1212",01850-509001,৳200–400 per person\nReported by 264 people,300.0,https://www.google.ca/maps/place/The+New+Gulsh...,Review 1 (4 stars): Apart from the very busy a...
2,Seasonal Tastes,4.6,"1,469",23.793366,90.414648,"The Westin, Main Gulshan Ave, Dhaka 1212",01730-304871,NaN,1000.0,https://www.google.ca/maps/place/Seasonal+Tast...,Review 1 (5 stars): Top notch display 🤯🤯one of...
3,Sultan's Dine Gulshan Branch,4.3,"11,475",23.794849,90.413267,"1st floor, Samsuddin Mansion, House: 41 Road: ...",NaN,৳400–600 per person\nReported by 864 people,2000.0,https://www.google.ca/maps/place/Sultan%27s+Di...,Review 1 (5 stars): Sultan's Dine in Gulshan i...
4,HEXA Dine - Restaurant & Café,4.2,740,23.791929,90.406217,"House: 34 (1st Floor), Green Regency, Road No:...",01886-439222,NaN,2000.0,https://www.google.ca/maps/place/HEXA+Dine+-+R...,Review 1 (5 stars): This is my first time visi...

In [123]:
data['sample_user_reviews'][0]

"Review 1 (4 stars): Clean food court. There are many food stalls. Prices are higher but quality is better than other food courts. Not extraordinary but good. Coffee shops, juice bar, and asian cuisine could be found.\n---\nReview 2 (4 stars): Clean food court. There are many food stalls. Prices are higher but quality is better than other food courts. Not extraordinary but good. Coffee shops, juice bar, and asian cuisine could be found.\n---\nReview 3 (5 stars): I recently visited Chef’s Table and had an absolutely wonderful experience. The restaurant offers a wide variety of dishes, each prepared with fresh ingredients and presented beautifully. The ambiance is modern yet cozy, making it perfect for both casual meals and special occasions. The staff were friendly, attentive, and made sure everything was perfect throughout the visit. The prices are reasonable considering the quality of food and service. I highly recommend Chef’s Table to anyone looking for a great dining experience.\n---\nReview 4 (5 stars): I recently visited Chef’s Table and had an absolutely wonderful experience. The restaurant offers a wide variety of dishes, each prepared with fresh ingredients and presented beautifully. The ambiance is modern yet cozy, making it perfect for both casual meals and special occasions. The staff were friendly, attentive, and made sure everything was perfect throughout the visit. The prices are reasonable considering the quality of food and service. I highly recommend Chef’s Table to anyone looking for a great dining experience.\n---\nReview 5 (5 stars): Chef’s Table in Gulshan 2 is a fantastic dining spot with a cozy and elegant ambiance. The food quality is excellent, with well-prepared dishes and great presentation.\n\nThe staff are attentive, polite, and provide good service, making the dining experience enjoyable. It’s an ideal place for family meals, casual outings, or special occasions. Overall, a highly recommended restaurant for anyone looking for delicious food in a pleasant setting. 🍽️✨\n---\nReview 6 (5 stars): Chef’s Table in Gulshan 2 is a fantastic dining spot with a cozy and elegant ambiance. The food quality is excellent, with well-prepared dishes and great presentation.\n\nThe staff are attentive, polite, and provide good service, making the dining experience enjoyable. It’s an ideal place for family meals, casual outings, or special occasions. Overall, a highly recommended restaurant for anyone looking for delicious food in a pleasant setting. 🍽️✨\n---\nReview 7 (5 stars): This is one of my favourite spots to hang out. It really offers something for everyone, whether you're after a quick snack or a full meal. The area is kept clean and well-maintained, providing a comfortable atmosphere to relax in. I’d certainly recommend it to others.\n---\nReview 8 (5 stars): This is one of my favourite spots to hang out. It really offers something for everyone, whether you're after a quick snack or a full meal. The area is kept clean and well-maintained, providing a comfortable atmosphere to relax in. I’d certainly recommend it to others.\n---\nReview 9 (4 stars): Place was good. Food quality was great.Different shop sell different foods. Atmosphere is soothing. Service was up to the mark. Decoration is different but top class. Food is costly. Drink, beverage and ice cream are not good enough to argue. Wash have separate space for handicapped people which is very good. They got playing zone for kids.\n---\nReview 10 (4 stars): Place was good. Food quality was great.Different shop sell different foods. Atmosphere is soothing. Service was up to the mark. Decoration is different but top class. Food is costly. Drink, beverage and ice cream are not good enough to argue. Wash have separate space for handicapped people which is very good. They got playing zone for kids.\n---\nReview 11 (3 stars): Food taste & quality is average.\nPrice is slightly higher.\n---\nReview 12 (3 stars): Food taste & quality is average.\nPrice is slightly higher.\n---\nReview 13 (5 stars): Chef’s Table is always only of my favourite places to spend some time with delicious different cuisines. As I never visit this branch, I intended to visit that with may family for dinner. There is nothing new to talk about this food court. Situated on Level 2 of the Gulshan Center Point, this food court is a popular destination for food enthusiasts seeking a variety of cuisines under one roof. Chef’s Table Gulshan 2 boasts an impressive array of food houses, each specializing in different cuisines. Whether you’re in the mood for Thai, Hakka Chinese, Deshi, Indian, or Italian, there’s something to satisfy every palate. The food court also offers healthy options like fresh juices, salads, and desserts, catering to those who prefer lighter fare. The atmosphere at Chef’s Table is lively and welcoming. The food court is designed to accommodate families and friends, making it an ideal spot for social gatherings. The clean and modern decor, combined with a spacious layout, ensures a comfortable dining experience. Additionally, there’s a play zone for kids, making it a family-friendly destination. Service at Chef’s Table Gulshan 2 is efficient and customer-focused. The staffs are known for their friendliness and attentiveness, ensuring that diners have a pleasant experience.\nIt’s a great place to spend some time with your loved ones.\n---\nReview 14 (5 stars): Chef’s Table is always only of my favourite places to spend some time with delicious different cuisines. As I never visit this branch, I intended to visit that with may family for dinner. There is nothing new to talk about this food court. Situated on Level 2 of the Gulshan Center Point, this food court is a popular destination for food enthusiasts seeking a variety of cuisines under one roof. Chef’s Table Gulshan 2 boasts an impressive array of food houses, each specializing in different cuisines. Whether you’re in the mood for Thai, Hakka Chinese, Deshi, Indian, or Italian, there’s something to satisfy every palate. The food court also offers healthy options like fresh juices, salads, and desserts, catering to those who prefer lighter fare. The atmosphere at Chef’s Table is lively and welcoming. The food court is designed to accommodate families and friends, making it an ideal spot for social gatherings. The clean and modern decor, combined with a spacious layout, ensures a comfortable dining experience. Additionally, there’s a play zone for kids, making it a family-friendly destination. Service at Chef’s Table Gulshan 2 is efficient and customer-focused. The staffs are known for their friendliness and attentiveness, ensuring that diners have a pleasant experience.\nIt’s a great place to spend some time with your loved ones.\n---\nReview 15 (5 stars): Good atmosphere for grouping and meeting. A huge variety of food including Indian, Korean, Turkish, and more.\n---\nReview 16 (5 stars): Good atmosphere for grouping and meeting. A huge variety of food including Indian, Korean, Turkish, and more.\n---\nReview 17 (5 stars): I tried grilled chicken with Naan, test was poor and not recommended.\nOnly the vegetables are good.\n---\nReview 18 (5 stars): I tried grilled chicken with Naan, test was poor and not recommended.\nOnly the vegetables are good.\n---\nReview 19 (5 stars): 🤩 Tips for First-Time Visitors\n* Seating is Flexible: Feel free to sit anywhere you like! It's completely normal (and often expected) to choose a table far away from the specific food outlets you're ordering from.\n* It's Self-Service: The setup is self-service, so you'll need to go directly to the various stalls to place and pick up your orders.\n* Mix and Match Your Meal: Don't feel restricted to one place! A major benefit of this chain is the ability to order from multiple available options (like different restaurants or stalls), allowing you to experience a variety of tastes all in one visit.\n* Children's Play Zone: Please note that the children's play zone is not free; there will be a charge for its use.\n---\nReview 20 (5 stars): 🤩 Tips for First-Time Visitors\n* Seating is Flexible: Feel free to sit anywhere you like! It's completely normal (and often expected) to choose a table far away from the specific food outlets you're ordering from.\n* It's Self-Service: The setup is self-service, so you'll need to go directly to the various stalls to place and pick up your orders.\n* Mix and Match Your Meal: Don't feel restricted to one place! A major benefit of this chain is the ability to order from multiple available options (like different restaurants or stalls), allowing you to experience a variety of tastes all in one visit.\n* Children's Play Zone: Please note that the children's play zone is not free; there will be a charge for its use.\n---\nReview 21 (5 stars): My friend and I had a fantastic time at Chef's Table - Gulshan 2. The variety of food options from the different vendors was incredible, so there was truly something for everyone. We ended up trying dishes from a few different places, and everything was delicious. The atmosphere was also great, with a lively and energetic vibe that made the experience even more enjoyable. It's a perfect spot for a casual meal with friends or family, and I'd highly recommend it to anyone looking for a fun and tasty dining experience.\n---\nReview 22 (5 stars): My friend and I had a fantastic time at Chef's Table - Gulshan 2. The variety of food options from the different vendors was incredible, so there was truly something for everyone. We ended up trying dishes from a few different places, and everything was delicious. The atmosphere was also great, with a lively and energetic vibe that made the experience even more enjoyable. It's a perfect spot for a casual meal with friends or family, and I'd highly recommend it to anyone looking for a fun and tasty dining experience.\n---\nReview 23 (5 stars): This chef's table has a variety of really great food options and cuisines to pick from. We had Turkish, Indian and Korean for our family dinner.\nExcellent quality and great ambience.\n5/5\n---\nReview 24 (5 stars): This chef's table has a variety of really great food options and cuisines to pick from. We had Turkish, Indian and Korean for our family dinner.\nExcellent quality and great ambience.\n5/5\n---\nReview 25 (5 stars): Had a great food experience at chefs table Gulshan 2. If you are looking for multi cuisine under one roof then it's a must visit place for you. So many options starting from continental to indian cuisine, they will surprise you with the taste and quality of food and the atmosphere was quite good.\n\nTheir dessert section is also great with varieties of cakes and other sweet items.\n\nDo visit the place\n---\nReview 26 (5 stars): Had a great food experience at chefs table Gulshan 2. If you are looking for multi cuisine under one roof then it's a must visit place for you. So many options starting from continental to indian cuisine, they will surprise you with the taste and quality of food and the atmosphere was quite good.\n\nTheir dessert section is also great with varieties of cakes and other sweet items.\n\nDo visit the place\n---\nReview 27 (5 stars): There's a wide range of foods available here: Bangladeshi, Cantonese, Mexican, Indian, Italian, Korean. You may also get fast food here. Really good atmosphere overall. Also, there's an arcade here. The washrooms are also well maintained.\n---\nReview 28 (5 stars): There's a wide range of foods available here: Bangladeshi, Cantonese, Mexican, Indian, Italian, Korean. You may also get fast food here. Really good atmosphere overall. Also, there's an arcade here. The washrooms are also well maintained.\n---\nReview 29 (4 stars): I tried the cheese brownie from Tabaq for 165 taka. It was delicious and had a soft, mashed texture. But I still think North End’s brownie is the best. Still, the Tabaq one was really good and worth a try.\n---\nReview 30 (4 stars): I tried the cheese brownie from Tabaq for 165 taka. It was delicious and had a soft, mashed texture. But I still think North End’s brownie is the best. Still, the Tabaq one was really good and worth a try.\n---\nReview 31 (4 stars): A wonderful and decorative place to hang out, the place was spacious.\n\nWe tried different items with variants.\nThe food prices may be slightly higher, but taste of some items is truly worth the price.\n\nWe tried foods from Mitsho, cilantro, Arax which was really great.\nTaste icecream from savoy at the end and really enjoy the foodie time. ⏲️\n---\nReview 32 (4 stars): A wonderful and decorative place to hang out, the place was spacious.\n\nWe tried different items with variants.\nThe food prices may be slightly higher, but taste of some items is truly worth the price.\n\nWe tried foods from Mitsho, cilantro, Arax which was really great.\nTaste icecream from savoy at the end and really enjoy the foodie time. ⏲️\n---\nReview 33 (4 stars): The salads were delicious. Wonderful experience. The dressing seemed extra special. Presentation was also exquisite.\nIt was absolutely worthy. You can choose from a variety of delightful options. All the dishes were fresh, delicious and tasted perfect.\nIt’s really a nice place to have a perfect meal with family or friends.\n---\nReview 34 (4 stars): The salads were delicious. Wonderful experience. The dressing seemed extra special. Presentation was also exquisite.\nIt was absolutely worthy. You can choose from a variety of delightful options. All the dishes were fresh, delicious and tasted perfect.\nIt’s really a nice place to have a perfect meal with family or friends.\n---\nReview 35 (5 stars): The lounge is a fantastic location with so many food options. A great family location too to bring in kids since they have a play area which you have to pay to avail.\n\nFood options include - Italian, Thai, continental, Asian, Indian and Western.\n\nFood varieties - pizza, pasta, burger, fried chicken, fried rice, Indian curry items, juice items (a bit expensive, imho), crepes, cheesecakes, and coffee.\n\nThere's a counter named Yoberries where you can get yoghurt with berries and fruits. Unfortunately, they run out of fruits quickly. If you ever want to be there, try it (a bit expensive though - close to 500tk.)\n---\nReview 36 (5 stars): The lounge is a fantastic location with so many food options. A great family location too to bring in kids since they have a play area which you have to pay to avail.\n\nFood options include - Italian, Thai, continental, Asian, Indian and Western.\n\nFood varieties - pizza, pasta, burger, fried chicken, fried rice, Indian curry items, juice items (a bit expensive, imho), crepes, cheesecakes, and coffee.\n\nThere's a counter named Yoberries where you can get yoghurt with berries and fruits. Unfortunately, they run out of fruits quickly. If you ever want to be there, try it (a bit expensive though - close to 500tk.)\n---\nReview 37 (5 stars): Pretty good place to chill and hang out. There are plenty of food options; Chinese, Thai, Korean, Indian and many more. There is a playing zone for kids. Teenagers can enjoy in gaming zone as well. Just like other food courts, it’s pay first and self service.\n---\nReview 38 (5 stars): Pretty good place to chill and hang out. There are plenty of food options; Chinese, Thai, Korean, Indian and many more. There is a playing zone for kids. Teenagers can enjoy in gaming zone as well. Just like other food courts, it’s pay first and self service.\n---\nReview 39 (4 stars): A delightful array of branded restaurants awaits you, along with a charming play area for children. 👧👦 While the food prices may be slightly higher, the ambiance is truly remarkable. 💰 For your convenience, there is a rooftop parking facility and a small mosque for daily prayers. 🕌 Do not miss out on the delectable Turkish ice cream, an absolute must-try. 🍦 Hakkadhaka is renowned for its exceptional Chinese cuisine, and kebab options are also available. 🇨🇳 Tabaque is good for coffee & snacks. ☕ Crisp is good for fast food items. 🍔\n---\nReview 40 (4 stars): A delightful array of branded restaurants awaits you, along with a charming play area for children. 👧👦 While the food prices may be slightly higher, the ambiance is truly remarkable. 💰 For your convenience, there is a rooftop parking facility and a small mosque for daily prayers. 🕌 Do not miss out on the delectable Turkish ice cream, an absolute must-try. 🍦 Hakkadhaka is renowned for its exceptional Chinese cuisine, and kebab options are also available. 🇨🇳 Tabaque is good for coffee & snacks. ☕ Crisp is good for fast food items. 🍔\n---\nReview 41 (5 stars): I recently visited [Gulshan 2 ] and I must say it was a delightful experience! The ambiance was warm and inviting, with tasteful decor that made the atmosphere feel both cozy and upscale.\n\nThe menu offered a great variety of dishes, and I decided to try the [dish name] along with a [drink/dessert]. The food was absolutely delicious – well-seasoned, perfectly cooked, and beautifully presented. It’s clear that they use fresh, high-quality ingredients.\n\nThe service was equally impressive. The staff were attentive, friendly, and knowledgeable about the menu. They made sure everything was to our liking without being overbearing.\n\nOverall, I highly recommend [Gulshan 2] to anyone looking for a great dining experience. I’ll definitely be returning soon!\n---\nReview 42 (5 stars): I recently visited [Gulshan 2 ] and I must say it was a delightful experience! The ambiance was warm and inviting, with tasteful decor that made the atmosphere feel both cozy and upscale.\n\nThe menu offered a great variety of dishes, and I decided to try the [dish name] along with a [drink/dessert]. The food was absolutely delicious – well-seasoned, perfectly cooked, and beautifully presented. It’s clear that they use fresh, high-quality ingredients.\n\nThe service was equally impressive. The staff were attentive, friendly, and knowledgeable about the menu. They made sure everything was to our liking without being overbearing.\n\nOverall, I highly recommend [Gulshan 2] to anyone looking for a great dining experience. I’ll definitely be returning soon!\n---\nReview 43 (5 stars): Good atmosphere for gathering, meeting , fun etc. You have plenty of choices. Different cuisines are available there. Kids zone, clean washroom, parking area, game zone . You will find all the things in one under the roof. Cheers 🥂\n---\nReview 44 (5 stars): Good atmosphere for gathering, meeting , fun etc. You have plenty of choices. Different cuisines are available there. Kids zone, clean washroom, parking area, game zone . You will find all the things in one under the roof. Cheers 🥂\n---\nReview 45 (4 stars): Went there tonight for dinner. I was craving Indian food since a few days and noticed Darbar.\nI took their butter chicken platter which comes with a butter naan, two pieces of reshmi kebab, dal makhani and of course butter chicken. It was 520 Tk.\nThe presentation was nice and the food looked absolutely yummy. But I really could not differentiate between the dal makhani and butter chicken. Both tasted the same to me. And the reshmi kebab was bland. Overall, the platter was just mediocre.\nThen I had devilled noodles from Taste of Lanka which comes with two chicken skewers and cost 419 Tk. It was a flavorful dish and good for people who loves spicy food.\nFinally, I had the red velvet cheesecake ice cream from savoy. The cost per scoop was 210 Tk! It was the best. I loved the texture of the ice cream. It was rich and creamy, topped with cheesecake crumbles and had the perfect tangy flavors of red velvet cake. It felt quite refreshing after a heavy meal, and it has become my new favorite ice cream flavor.\nI loved the place a lot. It was spacious and well decorated. I enjoyed the ambience! Planning to go there again soon.\n---\nReview 46 (4 stars): Went there tonight for dinner. I was craving Indian food since 

In [124]:
def replace_review_count(review_text):
    if isinstance(review_text, str):  
        return re.sub(r'Review (\d+) \(\d+ stars\):', r'\1:', review_text)
    return review_text  


data['sample_user_reviews'] = data['sample_user_reviews'].apply(replace_review_count)


print(data['sample_user_reviews'][2])

1: Top notch display 🤯🤯one of the best amd luxurious place in the city💥
---
2: Top notch display 🤯🤯one of the best amd luxurious place in the city💥
---
3: Absolutely loved the service! The staff were extremely polite and professional, and the atmosphere was relaxing. Would definitely recommend to anyone visiting Dhaka.
---
4: Absolutely loved the service! The staff were extremely polite and professional, and the atmosphere was relaxing. Would definitely recommend to anyone visiting Dhaka.
---
5: Went there for the Buffet, there was a huge selection of foods, many of them tasted good many of them didn't. There was a live kitchen for the grills and fries. 4 types of juices was available but no cold drinks, they asked 700 for one bottle of pepsi.
Environment was great, it was a 5 star experience in considering the environment but not the food.
Buffet cost was 4500+ per person.
---
6: Went there for the Buffet, there was a huge selection of foods, many of them tasted good many of them didn't. There was a live kitchen for the grills and fries. 4 types of juices was available but no cold drinks, they asked 700 for one bottle of pepsi.
Environment was great, it was a 5 star experience in considering the environment but not the food.
Buffet cost was 4500+ per person.
---
7: It was an amazing experience ngl, the service was excellent, but the food was below average.
You'll find different cuisines at the buffet, you'll get excited and want to try all of them. I'll suggest trying a small portion first, if you like it, just go for it.
Don't forget to try the fruits, especially the melon 🍈

Pro tip for any buffet: Ignore the rice, bread and drinks as much as you can, cause they are going to make you full.
---
8: It was an amazing experience ngl, the service was excellent, but the food was below average.
You'll find different cuisines at the buffet, you'll get excited and want to try all of them. I'll suggest trying a small portion first, if you like it, just go for it.
Don't forget to try the fruits, especially the melon 🍈

Pro tip for any buffet: Ignore the rice, bread and drinks as much as you can, cause they are going to make you full.
---
9: The food was fresh, flavorful, and beautifully presented. I especially enjoyed the live cooking stations where chefs prepare dishes right in front of you, adding a personal touch to the dining experience. Their seafood selection was impressive, and the desserts were both delicious and artfully arranged
---
10: The food was fresh, flavorful, and beautifully presented. I especially enjoyed the live cooking stations where chefs prepare dishes right in front of you, adding a personal touch to the dining experience. Their seafood selection was impressive, and the desserts were both delicious and artfully arranged
---
11: Went to seasonal taste for lunch. 4500tk+ per person.

Food - Their live cooking section was great. They cooked our picked items in front of us. Meat and fish items was fresh and delicious.
The dessert section was the best part of the buffet. Drinks were not included in the buffet so thats a bummer.

Service - Service was exceptional. Waiters and staffs were very helpful and polite.

Atmosphere - Atmosphere was nice and the place was very spacious. Chairs and utensils needs an upgrade.
---
12: Went to seasonal taste for lunch. 4500tk+ per person.

Food - Their live cooking section was great. They cooked our picked items in front of us. Meat and fish items was fresh and delicious.
The dessert section was the best part of the buffet. Drinks were not included in the buffet so thats a bummer.

Service - Service was exceptional. Waiters and staffs were very helpful and polite.

Atmosphere - Atmosphere was nice and the place was very spacious. Chairs and utensils needs an upgrade.
---
13: Cozy 5 star environment but the diversity of foods are not up to the mark. More continental foods should be included. Salads & appetizers need extra attention but shushi & sashimi are outstanding. I was hurt to hear that beef steaks were not available due to high price of beef. Staffs need to be more professional to prove their five star ratings. Finally the price which is much high in context of Bangladesh.
---
14: Cozy 5 star environment but the diversity of foods are not up to the mark. More continental foods should be included. Salads & appetizers need extra attention but shushi & sashimi are outstanding. I was hurt to hear that beef steaks were not available due to high price of beef. Staffs need to be more professional to prove their five star ratings. Finally the price which is much high in context of Bangladesh.
---
15: Had an amazing time at Seasonal Tastes, Gulshan! The buffet spread was diverse and well-balanced—loved the sushi, grilled prawns, and the live cooking stations. The ambiance is elegant and relaxing, perfect for a special night out. The service was top-notch—staff were attentive and made us feel welcome. A bit on the pricey side, but worth it for the quality and experience. Highly recommended for anyone looking to indulge!
---
16: Had an amazing time at Seasonal Tastes, Gulshan! The buffet spread was diverse and well-balanced—loved the sushi, grilled prawns, and the live cooking stations. The ambiance is elegant and relaxing, perfect for a special night out. The service was top-notch—staff were attentive and made us feel welcome. A bit on the pricey side, but worth it for the quality and experience. Highly recommended for anyone looking to indulge!
---
17: Good food, good service.
---
18: Good food, good service.
---
19: Seasonal Tastes is a relaxed  buffet restaurant inside The Westin. It's a place for luxury, comfort dining.  You'll get an elite aura inside the place. You'll be well assisted and served throughout the time. We had not a single dissatisfaction against their service and stuff.

Their stuff are very gentle, helpful, well behaved and mannered. They'll be at your service anytime.

Coming to their food, It's awesome. Yes, I've tried many buffets in Dhaka. And, I'll keep Westin at No. 1. They had lesser number of items in their buffet menu but had the tastiest and qualityful items. All the items I've tasted were equally delicious. Their Mutton Rogan Josh, Mutton Nihari are  top notch. Other significant items include lamb stew, lamb kefta, prawn fry from the live kitchen, dumplings, Arabinan Fish biriyani ( i forgot the exact name), Chicken Saslic, Tandori Chicken.

They've a tasty desert segment also. Gulab Jamoon, Rasagolla, different flavoured ice-creams, Different Pastries, Khonafa, Yogurt and others. All the items were good.

One thing I want to mention, they've a large space for the buffet but their decoration seemed very simple for me. They might think to add something in their Interior decoration.

The buffet is quite expensive. But for the service they provide, you need to pay.

Note: They don't include drinks in their buffet. So, you need to pay for it. You can also have juice instead of soft drinks.

Food: 9.5/10
Service: 10/10
Ambience : 8.5/10
---
20: Seasonal Tastes is a relaxed  buffet restaurant inside The Westin. It's a place for luxury, comfort dining.  You'll get an elite aura inside the place. You'll be well assisted and served throughout the time. We had not a single dissatisfaction against their service and stuff.

Their stuff are very gentle, helpful, well behaved and mannered. They'll be at your service anytime.

Coming to their food, It's awesome. Yes, I've tried many buffets in Dhaka. And, I'll keep Westin at No. 1. They had lesser number of items in their buffet menu but had the tastiest and qualityful items. All the items I've tasted were equally delicious. Their Mutton Rogan Josh, Mutton Nihari are  top notch. Other significant items include lamb stew, lamb kefta, prawn fry from the live kitchen, dumplings, Arabinan Fish biriyani ( i forgot the exact name), Chicken Saslic, Tandori Chicken.

They've a tasty desert segment also. Gulab Jamoon, Rasagolla, different flavoured ice-creams, Different Pastries, Khonafa, Yogurt and others. All the items were good.

One thing I want to mention, they've a large space for the buffet but their decoration seemed very simple for me. They might think to add something in their Interior decoration.

The buffet is quite expensive. But for the service they provide, you need to pay.

Note: They don't include drinks in their buffet. So, you need to pay for it. You can also have juice instead of soft drinks.

Food: 9.5/10
Service: 10/10
Ambience : 8.5/10
---
21: "I was pleasantly surprised by the salad platter as it was much better than expected. The flavours were blod and exciting."

"We are impressed by the genuine appreciation for their loyal customers . The staff made us feel welcome and valued."

"The soft lighting and comfortable seating made it perfect for a relax evening."
---
22: "I was pleasantly surprised by the salad platter as it was much better than expected. The flavours were blod and exciting."

"We are impressed by the genuine appreciation for their loyal customers . The staff made us feel welcome and valued."

"The soft lighting and comfortable seating made it perfect for a relax evening."
---
23: The food was absolutely delicious — every dish was full of flavor and beautifully presented. You can tell the ingredients were fresh and thoughtfully prepared. I highly recommend trying their [insert a dish name if known – e.g., “grilled lamb chops” or “signature pasta”].
---
24: The food was absolutely delicious — every dish was full of flavor and beautifully presented. You can tell the ingredients were fresh and thoughtfully prepared. I highly recommend trying their [insert a dish name if known – e.g., “grilled lamb chops” or “signature pasta”].
---
25: Great restaurants for any meal of the day. Located on second floor of Westin Hotel, the restaurant is the base for all food and beverages. It offer delightful decor and delicious Bangladeshi cuisine, served by very helpful and friendly staffs.
They had a lot of food items freshly made to order, customized to your taste and diet.

We visited in August 2021 and face masks are mandatory. The dishes and utensils were cleaned every 15-20 mins.
---
26: Great restaurants for any meal of the day. Located on second floor of Westin Hotel, the restaurant is the base for all food and beverages. It offer delightful decor and delicious Bangladeshi cuisine, served by very helpful and friendly staffs.
They had a lot of food items freshly made to order, customized to your taste and diet.

We visited in August 2021 and face masks are mandatory. The dishes and utensils were cleaned every 15-20 mins.
---
27: Went there for the Buffet, there was a huge selection of foods, many of them tasted good many of them. There was a live kitchen for the grills and fries. 4 types of juices was available. Overall, it is a very good hotel. I really liked their service and behavior.
---
28: Went there for the Buffet, there was a huge selection of foods, many of them tasted good many of them. There was a live kitchen for the grills and fries. 4 types of juices was available. Overall, it is a very good hotel. I really liked their service and behavior.
---
29: One of the best Restaurant I have ever seen. The food, the service and the aesthetics are unmatched. I had my most memorable moments there. Highly recommended 👌
---
30: One of the best Restaurant I have ever seen. The food, the service and the aesthetics are unmatched. I had my most memorable moments there. Highly recommended 👌
---
31: It was an amazing experience,
That was i give 5 star rating joint, exclusively designed to accommodate guest's comfort,  but it was good.
Buffet was wonderful and our group enjoyed a lot to have best dine.
Interior was very good. Awasom ❤️
---
32: It was an amazing experience,
That was i give 5 star rating joint, exclusively designed to accommodate guest's comfort,  but it was good.
Buffet was wonderful and our group enjoyed a lot to have best dine.
Interior was very good. Awasom ❤️
---
33: If you're looking for an exceptional dining experience in Dhaka, Seasonal Tastes at The Westin is a must-visit. Located in the heart of Gulshan, this restaurant offers a beautiful blend of sophistication and comfort. From the moment you step in, the elegant interior—featuring plush red seating and a stunning chandelier centerpiece—sets the mood for a luxurious meal.

The menu is a delightful mix of Pan-Asian a la carte and buffet options, catering to a wide range of palates. Whether you're craving authentic Asian cuisine or exploring new flavors, the dishes are always fresh, flavorful, and beautifully presented.

What truly stands out is the attentive service and peaceful atmosphere, making it ideal for both casual and special occasions. Being inside The Westin Dhaka adds a premium touch to the overall experience. It’s open until midnight, which is perfect for late dinners or relaxing after a long day.

Overall, Seasonal Tastes delivers on every front—ambience, taste, and service. Highly recommended for anyone seeking quality dining in Dhaka.
---
34: If you're looking for an exceptional dining experience in Dhaka, Seasonal Tastes at The Westin is a must-visit. Located in the heart of Gulshan, this restaurant offers a beautiful blend of sophistication and comfort. From the moment you step in, the elegant interior—featuring plush red seating and a stunning chandelier centerpiece—sets the mood for a luxurious meal.

The menu is a delightful mix of Pan-Asian a la carte and buffet options, catering to a wide range of palates. Whether you're craving authentic Asian cuisine or exploring new flavors, the dishes are always fresh, flavorful, and beautifully presented.

What truly stands out is the attentive service and peaceful atmosphere, making it ideal for both casual and special occasions. Being inside The Westin Dhaka adds a premium touch to the overall experience. It’s open until midnight, which is perfect for late dinners or relaxing after a long day.

Overall, Seasonal Tastes delivers on every front—ambience, taste, and service. Highly recommended for anyone seeking quality dining in Dhaka.
---
35: The atmosphere of the restaurant was awesome. Their food presentation and quality, i have never had anything in my entire life.It was a great experience go such a restaurant
---
36: The atmosphere of the restaurant was awesome. Their food presentation and quality, i have never had anything in my entire life.It was a great experience go such a restaurant
---
37: Its definitely a good restaurant. Nice interior, food and staff behaviour is 10 out of 10. Im satisfied and i hope you will also satisfied💗
---
38: Its definitely a good restaurant. Nice interior, food and staff behaviour is 10 out of 10. Im satisfied and i hope you will also satisfied💗
---
39: Great place to hangout with friends and family.Best food, Nice environment,Good behaviour. Best place to take pictures also.
---
40: Great place to hangout with friends and family.Best food, Nice environment,Good behaviour. Best place to take pictures also.
---
41: The Westin, Dhaka, located on Main Gulshan Avenue, delivers a reliable 5-star experience in the city’s prime diplomatic and business district. The rooms are spacious, quiet, and feature the signature Heavenly Bed—exceptionally comfortable for a restful sleep. Staff are professional and attentive, ensuring smooth check-in, housekeeping, and concierge service. The gym is well-maintained, and the indoor pool, though compact, is a welcome perk. Dining options like Seasons offer high-quality international buffets, especially for breakfast, though prices are on the higher side. The lobby lounge is great for meetings or a relaxing drink. While the hotel lacks strong local character—typical of global chains—it excels in cleanliness, comfort, and consistency. Wi-Fi is mostly reliable, though occasional dips occur in rooms. The location is a major plus, steps away from embassies, restaurants, and cafes. Ideal for business travelers and visitors seeking a polished, stress-free stay. While not the most luxurious in terms of design flair, it sets a high standard for service and comfort in Dhaka. Minor drawbacks don’t outweigh the overall quality.
---
42: The Westin, Dhaka, located on Main Gulshan Avenue, delivers a reliable 5-star experience in the city’s prime diplomatic and business district. The rooms are spacious, quiet, and feature the signature Heavenly Bed—exceptionally comfortable for a restful sleep. Staff are professional and attentive, ensuring smooth check-in, housekeeping, and concierge service. The gym is well-maintained, and the indoor pool, though compact, is a welcome perk. Dining options like Seasons offer high-quality international buffets, especially for breakfast, though prices are on the higher side. The lobby lounge is great for meetings or a relaxing drink. While the hotel lacks strong local character—typical of global chains—it excels in cleanliness, comfort, and consistency. Wi-Fi is mostly reliable, though occasional dips occur in rooms. The location is a major plus, steps away from embassies, restaurants, and cafes. Ideal for business travelers and visitors seeking a polished, stress-free stay. While not the most luxurious in terms of design flair, it sets a high standard for service and comfort in Dhaka. Minor drawbacks don’t outweigh the overall quality.
---
43: This hotei is a really 5 star hotel.This hotel food is very delicious. The best brunch in the city. Swimming pool access is included. More affordable with selected bank cards.
Thanks to the bank card offer.
---
44: This hotei is a really 5 star hotel.This hotel food is very delicious. The best brunch in the city. Swimming pool access is included. More affordable with selected bank cards.
Thanks to the bank card offer.
---
45: ---

🌟 A Delightful Dining Experience at The Westin Dhaka 🌟

I recently visited The Westin Dhaka and tried their biryani and desserts — and I must say, the experience was absolutely delightful!

The biryani was aromatic, perfectly cooked, and full of flavor. The meat was juicy and tender, and the rice was fluffy and well-seasoned — everything felt just right. It was a perfect balance of spices and texture.

Now let’s talk about the desserts — truly heavenly! 🍰
The chocolate mousse was rich, creamy, and melted in the mouth — a pure indulgence. And the mango pudding was refreshingly smooth with just the right sweetness, capturing the tropical essence beautifully. Both desserts were presented elegantly and tasted like premium quality treats.

The ambiance of the hotel was calm, clean, and beautifully decorated.
The staff were polite, attentive, and welcoming — excellent service all around.

I would gladly rate my dining experience at The Westin a solid 9.5 out of 10.
If you're looking for delicious food in a refined setting, The Westin Dhaka is definitely a place to try! ❤️
The westin main main Gulshan Ave Dhaka 1212 Bangladesh
---
46: ---

🌟 A Delightful Dining Experience at The Westin Dhaka 🌟

I recently visited The Westin Dhaka and tried their biryani and desserts — and I must say, the experience was absolutely delightful!

The biryani was aromatic, perfectly cooked, and full of flavor. The meat was juicy and tender, and the rice was fluffy and well-seasoned — everything felt just right. It was a perfect balance of spices and texture.

Now let’s talk about the desserts — truly heavenly! 🍰
The chocolate mousse was rich, creamy, and melted in the mouth — a pure indulgence. And the mango pudding was refreshingly smooth with just the right sweetness, capturing the tropical essence beautifully. Both desserts were presented elegantly and tasted like premium quality treats.

The ambiance of the hotel was calm, clean, and beautifully decorated.
The staff were polite, attentive, and welcoming — excellent service all around.

I would gladly rate my dining experience at The Westin a solid 9.5 out of 10.

In [125]:
data.head()

,name,rating,reviews_count,latitude,longitude,address,contact,price_range,price_per_person,map_url,sample_user_reviews
0,Chef's Table - Gulshan 2,4.5,"9,895",23.795731,90.414948,"Gulshan Centre Point, Dhaka 1212",01918-643663,NaN,700.0,https://www.google.ca/maps/place/Chef%27s+Tabl...,1: Clean food court. There are many food stall...
1,The New Gulshan Plaza Restaurant,4.2,"4,042",23.793650,90.414331,"33 Rd 45, Dhaka 1212",01850-509001,৳200–400 per person\nReported by 264 people,300.0,https://www.google.ca/maps/place/The+New+Gulsh...,"1: Apart from the very busy atmosphere, unclea..."
2,Seasonal Tastes,4.6,"1,469",23.793366,90.414648,"The Westin, Main Gulshan Ave, Dhaka 1212",01730-304871,NaN,1000.0,https://www.google.ca/maps/place/Seasonal+Tast...,1: Top notch display 🤯🤯one of the best amd lux...
3,Sultan's Dine Gulshan Branch,4.3,"11,475",23.794849,90.413267,"1st floor, Samsuddin Mansion, House: 41 Road: ...",NaN,৳400–600 per person\nReported by 864 people,2000.0,https://www.google.ca/maps/place/Sultan%27s+Di...,1: Sultan's Dine in Gulshan is one of the best...
4,HEXA Dine - Restaurant & Café,4.2,740,23.791929,90.406217,"House: 34 (1st Floor), Green Regency, Road No:...",01886-439222,NaN,2000.0,https://www.google.ca/maps/place/HEXA+Dine+-+R...,1: This is my first time visit in this restaur...

In [126]:
def remove_emojis(text):
    if isinstance(text, str):  
        emoji_pattern = re.compile(
            "[\U00010000-\U0010ffff"  
            "\u200d"                 
            "\u20e3"                  
            "\u2194-\u21AA"          
            "\u2300-\u23FF"           
            "\u2600-\u26FF"           
            "\u2700-\u27BF"          
            "\u2B50"                 
            "]+", flags=re.UNICODE)
        return emoji_pattern.sub(r'', text)
    return text  
data['sample_user_reviews'] = data['sample_user_reviews'].apply(remove_emojis)

In [127]:
data['sample_user_reviews'][3]

'1: Sultan\'s Dine in Gulshan is one of the best places in Dhaka for authentic and flavorful Kacchi Biryani. I have dined here multiple times, both with family and alone, and every visit has been a great experience. The biryani is rich, aromatic, and perfectly cooked, with tender, juicy meat and well-seasoned rice. The portion sizes are generous, making it worth the price. The restaurant has a clean, elegant ambiance, creating a comfortable dining experience. The service is excellent, with friendly and attentive staff ensuring quick and efficient service. I recently visited again, and the quality remains top-notch. Apart from Kacchi, their other dishes are also delicious and well-prepared. If you’re looking for the best Kacchi Biryani in Gulshan, Sultan’s Dine is the perfect place. Highly recommended for food lovers!\n---\n2: Sultan\'s Dine in Gulshan is one of the best places in Dhaka for authentic and flavorful Kacchi Biryani. I have dined here multiple times, both with family and alone, and every visit has been a great experience. The biryani is rich, aromatic, and perfectly cooked, with tender, juicy meat and well-seasoned rice. The portion sizes are generous, making it worth the price. The restaurant has a clean, elegant ambiance, creating a comfortable dining experience. The service is excellent, with friendly and attentive staff ensuring quick and efficient service. I recently visited again, and the quality remains top-notch. Apart from Kacchi, their other dishes are also delicious and well-prepared. If you’re looking for the best Kacchi Biryani in Gulshan, Sultan’s Dine is the perfect place. Highly recommended for food lovers!\n---\n3: I love sultan\'s dine. You can check out my review of their Mirpur Branch, as I have been there many times cause I live in Mirpur. But their Gulshan branch service was overwhelmingly bad, except the food.\nThe food was top, as always. We went there to try their newly launched Gorur Chap Polao. Also I didn\'t have their chicken dum biriyani before so went to have that too. It was a celebratory lunch for my girl\'s new achievement. But oh boy did they disappoint me with their service. The waiter completely forgot our order and kept serving others, even those who came and ordered after us.  He wasn\'t even responding to me when I called. Not to mention how our seat was robbed by some elderly and when I complained, the waiter just said \'I told them, what I can I do more?\' Totally disappointed with the service.\n\nComing to the food, the Chap Polao was nice, the meat was really huge in size considering it\'s only ৳220 with the polao. But the piece could\'ve been softer, it was a bit hard. They advertised the chap polao to be spicy but it ain\'t spicy at all. However, it\'s a good deal considering the price and portion. 8.5/10.\n\nNow coming to the Dum Biriyani - the chicken was sooooo goood, but the rice felt very dry, not very Sultan\'s type. I prefer their rice over any other kacchi joint solely because their rice is hella juicy and the gravy is plenty. For the Dum Biriyani, it was a bit disappointing cause it was dry, otherwise the meat and potato were really good. 7.5/10.\n\nEdit: 26 May - foodpanda\'d the Mutton Tehari (Full). It was decent. For 2,it\'s ৳439 meaning ৳220 per person. The rice was very neat, what we bengalis call \'ঝরঝরে\' and the meat to rice ratio was tbvh amazing! The meats were also very tender yet cut in a good proportion. Really loved the tehari, for this money this is legit the best in town. 9/10\n\nNo comments on the Borhani and Firni, as they\'re as usually good.\n---\n4: I love sultan\'s dine. You can check out my review of their Mirpur Branch, as I have been there many times cause I live in Mirpur. But their Gulshan branch service was overwhelmingly bad, except the food.\nThe food was top, as always. We went there to try their newly launched Gorur Chap Polao. Also I didn\'t have their chicken dum biriyani before so went to have that too. It was a celebratory lunch for my girl\'s new achievement. But oh boy did they disappoint me with their service. The waiter completely forgot our order and kept serving others, even those who came and ordered after us.  He wasn\'t even responding to me when I called. Not to mention how our seat was robbed by some elderly and when I complained, the waiter just said \'I told them, what I can I do more?\' Totally disappointed with the service.\n\nComing to the food, the Chap Polao was nice, the meat was really huge in size considering it\'s only ৳220 with the polao. But the piece could\'ve been softer, it was a bit hard. They advertised the chap polao to be spicy but it ain\'t spicy at all. However, it\'s a good deal considering the price and portion. 8.5/10.\n\nNow coming to the Dum Biriyani - the chicken was sooooo goood, but the rice felt very dry, not very Sultan\'s type. I prefer their rice over any other kacchi joint solely because their rice is hella juicy and the gravy is plenty. For the Dum Biriyani, it was a bit disappointing cause it was dry, otherwise the meat and potato were really good. 7.5/10.\n\nEdit: 26 May - foodpanda\'d the Mutton Tehari (Full). It was decent. For 2,it\'s ৳439 meaning ৳220 per person. The rice was very neat, what we bengalis call \'ঝরঝরে\' and the meat to rice ratio was tbvh amazing! The meats were also very tender yet cut in a good proportion. Really loved the tehari, for this money this is legit the best in town. 9/10\n\nNo comments on the Borhani and Firni, as they\'re as usually good.\n---\n5: This place is too crowded, and service was poor, hardly anyone listen when you call because too too busy.. and food wasn\'t that good either.. it was cold, one of the most average domm biriyani I ever had.. beef was average too, but the rice was good but again cold.. but the thing that is supposed to be cold ain\'t cold behh.. borhani and zafrani sorbod wasn\'t cold but I liked the zafrani sorbod.. my favorite..\nanyway i felt like this was one of the worst sultan dine experience I ever had .. because I\'m a regular customer there..\nNot recommend \n---\n6: This place is too crowded, and service was poor, hardly anyone listen when you call because too too busy.. and food wasn\'t that good either.. it was cold, one of the most average domm biriyani I ever had.. beef was average too, but the rice was good but again cold.. but the thing that is supposed to be cold ain\'t cold behh.. borhani and zafrani sorbod wasn\'t cold but I liked the zafrani sorbod.. my favorite..\nanyway i felt like this was one of the worst sultan dine experience I ever had .. because I\'m a regular customer there..\nNot recommend \n---\n7: They have limited but very tasty biryani options . I tried mutton biryani. Mutton was cooked perfectly it was tender and juicy. Also chiken Roast was good\n---\n8: They have limited but very tasty biryani options . I tried mutton biryani. Mutton was cooked perfectly it was tender and juicy. Also chiken Roast was good\n---\n9: I have been to this one for the first time, the dhanmondi one had good food but hope they can do better but the parking was a hassle and after the 17 minute of wait the rice was great and the meat(goat) was okay at best\n---\n10: I have been to this one for the first time, the dhanmondi one had good food but hope they can do better but the parking was a hassle and after the 17 minute of wait the rice was great and the meat(goat) was okay at best\n---\nReview 11 (N/A stars): Order no 127390\nPlaced on May 24, 2025\nOrdered for online delivery from Sultans Dine Official Website.\nOrdered at 12:54 pm\nDelivered at 3 pm\n5 packs of beef chap and polao. 1 pack had a decent chunk of beef. 3 others had 30%meat and 70%bone, and 1 had almost 95% bone with little to no beef. Adding a picture and a video of the one that had little to no meat in it.\n---\nReview 12 (N/A stars): Order no 127390\nPlaced on May 24, 2025\nOrdered for online delivery from Sultans Dine Official Website.\nOrdered at 12:54 pm\nDelivered at 3 pm\n5 packs of beef chap and polao. 1 pack had a decent chunk of beef. 3 others had 30%meat and 70%bone, and 1 had almost 95% bone with little to no beef. Adding a picture and a video of the one that had little to no meat in it.\n---\n13: Delicious food as always. But we faced some issues this time. The Pistachio juice(পেস্তাবাদামের জুস) was very light as if it was mixed with water. And the rice served was  a bit cold.\nService of the staffs were top notch. But other customers were too noisy. They were literally shouting and cheering loudly. The authority should at least warn them for the comfort of other customers.\n---\n14: Delicious food as always. But we faced some issues this time. The Pistachio juice(পেস্তাবাদামের জুস) was very light as if it was mixed with water. And the rice served was  a bit cold.\nService of the staffs were top notch. But other customers were too noisy. They were literally shouting and cheering loudly. The authority should at least warn them for the comfort of other customers.\n---\n15: The restaurant was good enough for a gathering and the interior was quite fine.\nThe complaint is about portion size. The chicken roast piece was so small that I could not even finish my meal. How on earth did they provide such a small portion for lunch, only Allah knows.\nThey provided a dish of Polaw which was good enough, but could not finish as my chicken was finished.\nFood taste was 7/10 yet too oily. Borhani was good. Water was the best amongst my purchases.\n---\n16: The restaurant was good enough for a gathering and the interior was quite fine.\nThe complaint is about portion size. The chicken roast piece was so small that I could not even finish my meal. How on earth did they provide such a small portion for lunch, only Allah knows.\nThey provided a dish of Polaw which was good enough, but could not finish as my chicken was finished.\nFood taste was 7/10 yet too oily. Borhani was good. Water was the best amongst my purchases.\n---\n17: The best biryani in Dhaka.\nIt is well cooked, aromatic and rich  flavor with tender juicy meat. Fully recommend.\n---\n18: The best biryani in Dhaka.\nIt is well cooked, aromatic and rich  flavor with tender juicy meat. Fully recommend.\n---\n19: Food quality is average, and it was little bit more salty.\n---\n20: Food quality is average, and it was little bit more salty.\n---\nReview 21 (N/A stars): Avoid this sultan branch in Gulshan.\nunfortunately the food was not satisfied because the meat burned.\nStuff are not friendly and careless. Behave of the stuff should be more friendly. Mutton pieces were so dry, I expected more tenderness. The rice itself felt a bit dry. Over over a disappointment.\nDecided to go to another place for lunch. Probably won\'t go there ever again.\n---\nReview 22 (N/A stars): Avoid this sultan branch in Gulshan.\nunfortunately the food was not satisfied because the meat burned.\nStuff are not friendly and careless. Behave of the stuff should be more friendly. Mutton pieces were so dry, I expected more tenderness. The rice itself felt a bit dry. Over over a disappointment.\nDecided to go to another place for lunch. Probably won\'t go there ever again.\n---\n23: We went to this branch on last month for beef chap specially! So at first they said this is not available and need 2 hours to make it! Ok me and my friends said that we are waiting then. They said you can\'t wait this long. So I got furious and asked for their manager. Then they said ok give us 10 minutes we are serving.\nAnd exactly after 10 minutes they served hot and fully cooked beef chap.\n\nMy question is how come is this happened?  Like 2 hours converted into 10 minutes?\n\nAlso during billing they took 230 tk per beef chap saying that the price has been increased.  We didn’t bother then but 2 days ago I again ate beef chap on another branch with 220 tk.\n\nI Don\'t know what\'s wrong with the Gulshan branch. Highly not recommending this place.\n---\n24: We went to this branch on last month for beef chap specially! So at first they said this is not available and need 2 hours to make it! Ok me and my friends said that we are waiting then. They said you can\'t wait this long. So I got furious and asked for their manager. Then they said ok give us 10 minutes we are serving.\nAnd exactly after 10 minutes they served hot and fully cooked beef chap.\n\nMy question is how come is this happened?  Like 2 hours converted into 10 minutes?\n\nAlso during billing they took 230 tk per beef chap saying that the price has been increased.  We didn’t bother then but 2 days ago I again ate beef chap on another branch with 220 tk.\n\nI Don\'t know what\'s wrong with the Gulshan branch. Highly not recommending this place.\n---\n25: One of the best kachhi places in Dhaka city. They are famous for their kachhi. They have all other food items like tehari, chicken dum biryani, chicken roast, borhani and many more. But they nailed it in Kachhi. Recently I tried their chicken dum biryani that is not up to the mark. The interior is quite good. It\'s a great place to visit with friends and family. The behaviour of the staff is professional and friendly. They have a well maintained washroom and refreshing area.\n---\n26: One of the best kachhi places in Dhaka city. They are famous for their kachhi. They have all other food items like tehari, chicken dum biryani, chicken roast, borhani and many more. But they nailed it in Kachhi. Recently I tried their chicken dum biryani that is not up to the mark. The interior is quite good. It\'s a great place to visit with friends and family. The behaviour of the staff is professional and friendly. They have a well maintained washroom and refreshing area.\n---\n27: I think 2 is enough, Food\'s tastes are average and not special as branding but the amount is enough. Staff\'s behaviour is careless, after finishing the dining when I paying the bill then I could know that their have no online payment system which made me shocked & disappointed because I had no cash except card/bkash, and as a big restaurant  i think should have online payment system. After all I had to pay by bkash with cash out charge ..... I hope management will implement this payment option to ensure the customers satisfaction\n---\n28: I think 2 is enough, Food\'s tastes are average and not special as branding but the amount is enough. Staff\'s behaviour is careless, after finishing the dining when I paying the bill then I could know that their have no online payment system which made me shocked & disappointed because I had no cash except card/bkash, and as a big restaurant  i think should have online payment system. After all I had to pay by bkash with cash out charge ..... I hope management will implement this payment option to ensure the customers satisfaction\n---\n29: One of the best Kacchi I had on this Gulshan Branch among the other branch of Sultanbs Dine. Mostly this branch is famous for chicken item but the Kacchi item is also awesome.\nThe mutton was well cooked & it was delicious to eat. The rice was also good.\nThis branch has big length d accommodate many customer once at a time. They have wide section for a group of friends or family.  Also couple seats are available.\nThe service was good & they handled the customer politely.\nPersonally I don\'t like the washroom system. It is not enough as the ratio of the customers. Also the placement of washroom just beside the kitchen & there is no separate section.\nOverall recommended \n---\n30: One of the best Kacchi I had on this Gulshan Branch among the other branch of Sultanbs Dine. Mostly this branch is famous for chicken item but the Kacchi item is also awesome.\nThe mutton was well cooked & it was delicious to eat. The rice was also good.\nThis branch has big length d accommodate many customer once at a time. They have wide section for a group of friends or family.  Also couple seats are available.\nThe service was good & they handled the customer politely.\nPersonally I don\'t like the washroom system. It is not enough as the ratio of the customers. Also the placement of washroom just beside the kitchen & there is no separate section.\nOverall recommended \n---\nReview 31 (N/A stars): Not satisfied as they brand themselves.  a boy came and said that it is not on the menu and tried to order another!\nHonestly, so unprofessional. Now about food. Not worthy to buy at this rate. Moreover,they have controversial news . Even their AC was off and there was no lift and generator.\n\n***I would never go to this restaurant ever in My life***\n---\nReview 32 (N/A stars): Not satisfied as they brand themselves.  a boy came and said that it is not on the menu and tried to order another!\nHonestly, so unprofessional. Now about food. Not worthy to buy at this rate. Moreover,they have controversial news . Even their AC was off and there was no lift and generator.\n\n***I would never go to this restaurant ever in My life***\n---\n33: Good food, though tad pricey. Very friendly service and menu is easy to review by English speaking foreigners.\nWe ordered the kacchi biryani platter and it came with the mutton biryani, chicken, some more meat, potato fritter, dessert, and drink. Though the boryani could use more meat, the taste did not disappoint. Will definitely come back when in Dhaka again.\n---\n34: Good food, though tad pricey. Very friendly service and menu is easy to review by English speaking foreigners.\nWe ordered the kacchi biryani platter and it came with the mutton biryani, chicken, some more meat, potato fritter, dessert, and drink. Though the boryani could use more meat, the taste did not disappoint. Will definitely come back when in Dhaka again.\n---\n35: Sultan’s Dine Gulshan is an absolute gem when it comes to Mutton Kacchi. I recently treated my team to celebrate landing a permanent job, and it was the perfect choice. The food here is not only plentiful but bursting with flavor. Each bite of the Mutton Kacchi was a delight to the senses, leaving us craving for more.\n\nWhat truly impressed me was the improved service. The staff went above and beyond to ensure our dining experience was top-notch. They were attentive, friendly, and truly enhanced our celebration.\n\nI wholeheartedly recommend Sultan’s Dine Gulshan to anyone craving authentic and delicious Mutton Kacchi. Whether it’s a special occasion or just a craving for fantastic food, this place delivers every time. From the moment we walked in until the last bite, we were thoroughly impressed. Thank you, Sultan’s Dine Gulshan, for making our celebration memorable. We\'ll definitely be back for more!\n---\n36: Sultan’s Dine Gulshan is an absolute gem when it comes to Mutton Kacchi. I recently treated my team to celebrate landing a permanent job, and it was the perfect choice. The food here is not only plentiful but bursting with flavor. Each bite of the Mutton Kacchi was a delight to the senses, leaving us craving for more.\n\nWhat truly impressed me was the improved service. The staff went above and beyond to ensure our dining experience was top-notch. They were attentive, friendly, and truly enhanced our celebration.\n\nI wholeheartedly recommend Sultan’s Dine Gulshan to anyone craving authentic and delicious Mutton Kacchi. Whether it’s a special occasion or just a craving for fantastic food, this place delivers every time. From the moment we walked in until the last bite, we were thoroughly impressed. Thank you, Sultan’s Dine Gulshan, for making our celebration memorable. We\'ll definitely be back for more!\n---\n37: Food Decoration Unsatisfied .\nBut,Food Taste is the Best Test in town.\n---\n38: Food Decoration Unsatisfied .\nBut,Food Taste is the Best Test in town.\n---\n39: A heartfelt thank you to Sultans Dine! Our group of eight found ourselves in a bit of a predicament, craving kacchi but unable to find a restaurant with availability due to Shob-e-Borat festivities. Thankfully, Sultans Dine came to our rescue, promisin

In [128]:
missing_values = data.isna().sum()
print(missing_values)

name                     0
rating                   0
reviews_count            0
latitude                 0
longitude                0
address                  1
contact                 65
price_range            261
price_per_person         0
map_url                  0
sample_user_reviews      1
dtype: int64

In [129]:
data.dtypes

name                    object
rating                 float64
reviews_count           object
latitude               float64
longitude              float64
address                 object
contact                 object
price_range             object
price_per_person       float64
map_url                 object
sample_user_reviews     object
dtype: object

In [130]:
data.drop(columns=['price_range'], inplace=True)

data['contact'] = data['contact'].astype(str).fillna('Unknown')

In [131]:
missing_values = data.isna().sum()
print(missing_values)

name                   0
rating                 0
reviews_count          0
latitude               0
longitude              0
address                1
contact                0
price_per_person       0
map_url                0
sample_user_reviews    1
dtype: int64

In [132]:
missing_rows = data[data.isna().any(axis=1)]
print(missing_rows)

     name  rating reviews_count   latitude  longitude address contact  \
267  Soi7     4.1         2,596  23.744622  90.380529     NaN     nan

     price_per_person                                            map_url  \
267             450.0  https://www.google.ca/maps/place/Soi7/data=!4m...

    sample_user_reviews
267                 NaN

In [133]:
data = data.dropna(subset=['sample_user_reviews'])

In [134]:
missing_values = data.isna().sum()
print(missing_values)

name                   0
rating                 0
reviews_count          0
latitude               0
longitude              0
address                0
contact                0
price_per_person       0
map_url                0
sample_user_reviews    0
dtype: int64

In [135]:
# Convert 'reviews_count' to numeric by removing commas and changing it to integer
data['reviews_count'] = data['reviews_count'].str.replace(',', '').astype(int)

# Fill missing 'contact' values with "Unknown"
data['contact'] = data['contact'].fillna('Unknown')

In [136]:
missing_values = data.isna().sum()
print(missing_values)

name                   0
rating                 0
reviews_count          0
latitude               0
longitude              0
address                0
contact                0
price_per_person       0
map_url                0
sample_user_reviews    0
dtype: int64

In [137]:
# Replace NaN in 'contact' with 'Unknown'
data['contact'] = data['contact'].fillna('Unknown')

# Clean 'sample_user_reviews' column by removing line breaks and special characters
data['sample_user_reviews'] = data['sample_user_reviews'].str.replace(r'[\n\r]+', ' ', regex=True)

In [138]:
column_counts = data.apply(lambda row: len(row), axis=1)
print(column_counts.value_counts())

10    577
Name: count, dtype: int64

In [139]:
data = data.dropna(axis=1, how='all') 
data = data.dropna(how='all')

In [140]:
missing_values = data.isna().sum()
print(missing_values)

name                   0
rating                 0
reviews_count          0
latitude               0
longitude              0
address                0
contact                0
price_per_person       0
map_url                0
sample_user_reviews    0
dtype: int64

In [141]:
data.dtypes

name                    object
rating                 float64
reviews_count            int64
latitude               float64
longitude              float64
address                 object
contact                 object
price_per_person       float64
map_url                 object
sample_user_reviews     object
dtype: object

In [142]:
cleaned_file_path = '/home/rifat/Documents/feastAI/updated_eda_data.csv'

data.to_csv(cleaned_file_path, index=False)

print(f"Data has been saved as '{cleaned_file_path}'")

Data has been saved as '/home/rifat/Documents/feastAI/updated_eda_data.csv'

In [151]:
import mysql.connector
import pandas as pd

# Database connection parameters
db_connection = mysql.connector.connect(
    host="localhost", 
    user="mukul", 
    password="mukul1572", 
    database="feast_ai"
)

# Create a cursor object
cursor = db_connection.cursor()

# Print connection details (optional)
print(db_connection)
# print(cursor)

<mysql.connector.connection_cext.CMySQLConnection object at 0x7fa4b04de110>

In [144]:
# # Make sure the database connection and cursor are already established

# # Loop through the data and insert into the database
# for index, row in data.iterrows():
#     # Prepare the insert statement
#     insert_query = """
#     INSERT INTO restaurants (name, rating, reviews_count, latitude, longitude, address, contact, price_per_person, map_url, sample_user_reviews)
#     VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
#     """
    
#     # Values from the DataFrame row
#     values = (
#         row['name'], 
#         row['rating'], 
#         row['reviews_count'], 
#         row['latitude'], 
#         row['longitude'], 
#         row['address'], 
#         row['contact'], 
#         row['price_per_person'], 
#         row['map_url'], 
#         row['sample_user_reviews']
#     )
    
#     # Execute the query
#     cursor.execute(insert_query, values)
    
#     # Commit the transaction
#     db_connection.commit()

# # Close the cursor and connection after completion
# cursor.close()
# db_connection.close()

In [152]:
# Reconnect to the database if necessary to validate
# db_connection = mysql.connector.connect(
#     host="localhost", 
#     user="mukul", 
#     password="mukul1572", 
#     database="feast_ai"
# )
cursor = db_connection.cursor()

# Query to check the uploaded data
cursor.execute("SELECT * FROM restaurants LIMIT 10;")
result = cursor.fetchall()

# Print the result
for row in result:
    print(row)

cursor.close()
db_connection.close()

(1, "Chef's Table - Gulshan 2", 4.5, 9895, 23.7957308, 90.4149481, 'Gulshan Centre Point, Dhaka 1212', '01918-643663', Decimal('700.00'), 'https://www.google.ca/maps/place/Chef%27s+Table+-+Gulshan+2/data=!4m7!3m6!1s0x3755c7429b9b4369:0xb10937f2b0542529!8m2!3d23.7957308!4d90.4149481!16s%2Fg%2F11f7bgg1tf!19sChIJaUObm0LHVTcRKSVUsPI3CbE?authuser=0&hl=en&rclk=1', "1: Clean food court. There are many food stalls. Prices are higher but quality is better than other food courts. Not extraordinary but good. Coffee shops, juice bar, and asian cuisine could be found. --- 2: Clean food court. There are many food stalls. Prices are higher but quality is better than other food courts. Not extraordinary but good. Coffee shops, juice bar, and asian cuisine could be found. --- 3: I recently visited Chef’s Table and had an absolutely wonderful experience. The restaurant offers a wide variety of dishes, each prepared with fresh ingredients and presented beautifully. The ambiance is modern yet cozy, making it perfect for both casual meals and special occasions. The staff were friendly, attentive, and made sure everything was perfect throughout the visit. The prices are reasonable considering the quality of food and service. I highly recommend Chef’s Table to anyone looking for a great dining experience. --- 4: I recently visited Chef’s Table and had an absolutely wonderful experience. The restaurant offers a wide variety of dishes, each prepared with fresh ingredients and presented beautifully. The ambiance is modern yet cozy, making it perfect for both casual meals and special occasions. The staff were friendly, attentive, and made sure everything was perfect throughout the visit. The prices are reasonable considering the quality of food and service. I highly recommend Chef’s Table to anyone looking for a great dining experience. --- 5: Chef’s Table in Gulshan 2 is a fantastic dining spot with a cozy and elegant ambiance. The food quality is excellent, with well-prepared dishes and great presentation. The staff are attentive, polite, and provide good service, making the dining experience enjoyable. It’s an ideal place for family meals, casual outings, or special occasions. Overall, a highly recommended restaurant for anyone looking for delicious food in a pleasant setting. ️ --- 6: Chef’s Table in Gulshan 2 is a fantastic dining spot with a cozy and elegant ambiance. The food quality is excellent, with well-prepared dishes and great presentation. The staff are attentive, polite, and provide good service, making the dining experience enjoyable. It’s an ideal place for family meals, casual outings, or special occasions. Overall, a highly recommended restaurant for anyone looking for delicious food in a pleasant setting. ️ --- 7: This is one of my favourite spots to hang out. It really offers something for everyone, whether you're after a quick snack or a full meal. The area is kept clean and well-maintained, providing a comfortable atmosphere to relax in. I’d certainly recommend it to others. --- 8: This is one of my favourite spots to hang out. It really offers something for everyone, whether you're after a quick snack or a full meal. The area is kept clean and well-maintained, providing a comfortable atmosphere to relax in. I’d certainly recommend it to others. --- 9: Place was good. Food quality was great.Different shop sell different foods. Atmosphere is soothing. Service was up to the mark. Decoration is different but top class. Food is costly. Drink, beverage and ice cream are not good enough to argue. Wash have separate space for handicapped people which is very good. They got playing zone for kids. --- 10: Place was good. Food quality was great.Different shop sell different foods. Atmosphere is soothing. Service was up to the mark. Decoration is different but top class. Food is costly. Drink, beverage and ice cream are not good enough to argue. Wash have separate space for handicapped people which is very good. They got playing zone for kids. --- 11: Food taste & quality is average. Price is slightly higher. --- 12: Food taste & quality is average. Price is slightly higher. --- 13: Chef’s Table is always only of my favourite places to spend some time with delicious different cuisines. As I never visit this branch, I intended to visit that with may family for dinner. There is nothing new to talk about this food court. Situated on Level 2 of the Gulshan Center Point, this food court is a popular destination for food enthusiasts seeking a variety of cuisines under one roof. Chef’s Table Gulshan 2 boasts an impressive array of food houses, each specializing in different cuisines. Whether you’re in the mood for Thai, Hakka Chinese, Deshi, Indian, or Italian, there’s something to satisfy every palate. The food court also offers healthy options like fresh juices, salads, and desserts, catering to those who prefer lighter fare. The atmosphere at Chef’s Table is lively and welcoming. The food court is designed to accommodate families and friends, making it an ideal spot for social gatherings. The clean and modern decor, combined with a spacious layout, ensures a comfortable dining experience. Additionally, there’s a play zone for kids, making it a family-friendly destination. Service at Chef’s Table Gulshan 2 is efficient and customer-focused. The staffs are known for their friendliness and attentiveness, ensuring that diners have a pleasant experience. It’s a great place to spend some time with your loved ones. --- 14: Chef’s Table is always only of my favourite places to spend some time with delicious different cuisines. As I never visit this branch, I intended to visit that with may family for dinner. There is nothing new to talk about this food court. Situated on Level 2 of the Gulshan Center Point, this food court is a popular destination for food enthusiasts seeking a variety of cuisines under one roof. Chef’s Table Gulshan 2 boasts an impressive array of food houses, each specializing in different cuisines. Whether you’re in the mood for Thai, Hakka Chinese, Deshi, Indian, or Italian, there’s something to satisfy every palate. The food court also offers healthy options like fresh juices, salads, and desserts, catering to those who prefer lighter fare. The atmosphere at Chef’s Table is lively and welcoming. The food court is designed to accommodate families and friends, making it an ideal spot for social gatherings. The clean and modern decor, combined with a spacious layout, ensures a comfortable dining experience. Additionally, there’s a play zone for kids, making it a family-friendly destination. Service at Chef’s Table Gulshan 2 is efficient and customer-focused. The staffs are known for their friendliness and attentiveness, ensuring that diners have a pleasant experience. It’s a great place to spend some time with your loved ones. --- 15: Good atmosphere for grouping and meeting. A huge variety of food including Indian, Korean, Turkish, and more. --- 16: Good atmosphere for grouping and meeting. A huge variety of food including Indian, Korean, Turkish, and more. --- 17: I tried grilled chicken with Naan, test was poor and not recommended. Only the vegetables are good. --- 18: I tried grilled chicken with Naan, test was poor and not recommended. Only the vegetables are good. --- 19:  Tips for First-Time Visitors * Seating is Flexible: Feel free to sit anywhere you like! It's completely normal (and often expected) to choose a table far away from the specific food outlets you're ordering from. * It's Self-Service: The setup is self-service, so you'll need to go directly to the various stalls to place and pick up your orders. * Mix and Match Your Meal: Don't feel restricted to one place! A major benefit of this chain is the ability to order from multiple available options (like different restaurants or stalls), allowing you to experience a variety of tastes all in one visit. * Children's Play Zone: Please note that the children's play zone is not free; there will be a charge for its use. --- 20:  Tips for First-Time Visitors * Seating is Flexible: Feel free to sit anywhere you like! It's completely normal (and often expected) to choose a table far away from the specific food outlets you're ordering from. * It's Self-Service: The setup is self-service, so you'll need to go directly to the various stalls to place and pick up your orders. * Mix and Match Your Meal: Don't feel restricted to one place! A major benefit of this chain is the ability to order from multiple available options (like different restaurants or stalls), allowing you to experience a variety of tastes all in one visit. * Children's Play Zone: Please note that the children's play zone is not free; there will be a charge for its use. --- 21: My friend and I had a fantastic time at Chef's Table - Gulshan 2. The variety of food options from the different vendors was incredible, so there was truly something for everyone. We ended up trying dishes from a few different places, and everything was delicious. The atmosphere was also great, with a lively and energetic vibe that made the experience even more enjoyable. It's a perfect spot for a casual meal with friends or family, and I'd highly recommend it to anyone looking for a fun and tasty dining experience. --- 22: My friend and I had a fantastic time at Chef's Table - Gulshan 2. The variety of food options from the different vendors was incredible, so there was truly something for everyone. We ended up trying dishes from a few different places, and everything was delicious. The atmosphere was also great, with a lively and energetic vibe that made the experience even more enjoyable. It's a perfect spot for a casual meal with friends or family, and I'd highly recommend it to anyone looking for a fun and tasty dining experience. --- 23: This chef's table has a variety of really great food options and cuisines to pick from. We had Turkish, Indian and Korean for our family dinner. Excellent quality and great ambience. 5/5 --- 24: This chef's table has a variety of really great food options and cuisines to pick from. We had Turkish, Indian and Korean for our family dinner. Excellent quality and great ambience. 5/5 --- 25: Had a great food experience at chefs table Gulshan 2. If you are looking for multi cuisine under one roof then it's a must visit place for you. So many options starting from continental to indian cuisine, they will surprise you with the taste and quality of food and the atmosphere was quite good. Their dessert section is also great with varieties of cakes and other sweet items. Do visit the place --- 26: Had a great food experience at chefs table Gulshan 2. If you are looking for multi cuisine under one roof then it's a must visit place for you. So many options starting from continental to indian cuisine, they will surprise you with the taste and quality of food and the atmosphere was quite good. Their dessert section is also great with varieties of cakes and other sweet items. Do visit the place --- 27: There's a wide range of foods available here: Bangladeshi, Cantonese, Mexican, Indian, Italian, Korean. You may also get fast food here. Really good atmosphere overall. Also, there's an arcade here. The washrooms are also well maintained. --- 28: There's a wide range of foods available here: Bangladeshi, Cantonese, Mexican, Indian, Italian, Korean. You may also get fast food here. Really good atmosphere overall. Also, there's an arcade here. The washrooms are also well maintained. --- 29: I tried the cheese brownie from Tabaq for 165 taka. It was delicious and had a soft, mashed texture. But I still think North End’s brownie is the best. Still, the Tabaq one was really good and worth a try. --- 30: I tried the cheese brownie from Tabaq for 165 taka. It was delicious and had a soft, mashed texture. But I still think North End’s brownie is the best. Still, the Tabaq one was really good and worth a try. --- 31: A wonderful and decorative place to hang out, the place was spacious. We tried different items with variants. The food prices may be slightly higher, but taste of some items is truly worth the price. We tried foods from Mitsho, cilantro, Arax which was really great. Taste icecream from savoy at the end and really enjoy the foodie time. ️ --- 32: A wonderful and decorative place to hang out, the place was spacious. We tried different items with variants. The food prices may be slightly higher, but taste of some items is truly worth the price. We tried foods from Mitsho, cilantro, Arax which was really great. Taste icecream from savoy at the end and really enjoy the foodie time. ️ --- 33: The salads were delicious. Wonderful experience. The dressing seemed extra special. Presentation was also exquisite. It was absolutely worthy. You can choose from a variety of delightful options. All the dishes were fresh, delicious and tasted perfect. It’s really a nice place to have a perfect meal with family or friends. --- 34: The salads were delicious. Wonderful experience. The dressing seemed extra special. Presentation was also exquisite. It was absolutely worthy. You can choose from a variety of delightful options. All the dishes were fresh, delicious and tasted perfect. It’s really a nice place to have a perfect meal with family or friends. --- 35: The lounge is a fantastic location with so many food options. A great family location too to bring in kids since they have a play area which you have to pay to avail. Food options include - Italian, Thai, continental, Asian, Indian and Western. Food varieties - pizza, pasta, burger, fried chicken, fried rice, Indian curry items, juice items (a bit expensive, imho), crepes, cheesecakes, and coffee. There's a counter named Yoberries where you can get yoghurt with berries and fruits. Unfortunately, they run out of fruits quickly. If you ever want to be there, try it (a bit expensive though - close to 500tk.) --- 36: The lounge is a fantastic location with so many food options. A great family location too to bring in kids since they have a play area which you have to pay to avail. Food options include - Italian, Thai, continental, Asian, Indian and Western. Food varieties - pizza, pasta, burger, fried chicken, fried rice, Indian curry items, juice items (a bit expensive, imho), crepes, cheesecakes, and coffee. There's a counter named Yoberries where you can get yoghurt with berries and fruits. Unfortunately, they run out of fruits quickly. If you ever want to be there, try it (a bit expensive though - close to 500tk.) --- 37: Pretty good place to chill and hang out. There are plenty of food options; Chinese, Thai, Korean, Indian and many more. There is a playing zone for kids. Teenagers can enjoy in gaming zone as well. Just like other food courts, it’s pay first and self service. --- 38: Pretty good place to chill and hang out. There are plenty of food options; Chinese, Thai, Korean, Indian and many more. There is a playing zone for kids. Teenagers can enjoy in gaming zone as well. Just like other food courts, it’s pay first and self service. --- 39: A delightful array of branded restaurants awaits you, along with a charming play area for children.  While the food prices may be slightly higher, the ambiance is truly remarkable.  For your convenience, there is a rooftop parking facility and a small mosque for daily prayers.  Do not miss out on the delectable Turkish ice cream, an absolute must-try.  Hakkadhaka is renowned for its exceptional Chinese cuisine, and kebab options are also available.  Tabaque is good for coffee & snacks.  Crisp is good for fast food items.  --- 40: A delightful array of branded restaurants awaits you, along with a charming play area for children.  While the food prices may be slightly higher, the ambiance is truly remarkable.  For your convenience, there is a rooftop parking facility and a small mosque for daily prayers.  Do not miss out on the delectable Turkish ice cream, an absolute must-try.  Hakkadhaka is renowned for its exceptional Chinese cuisine, and kebab options are also available.  Tabaque is good for coffee & snacks.  Crisp is good for fast food items.  --- 41: I recently visited [Gulshan 2 ] and I must say it was a delightful experience! The ambiance was warm and inviting, with tasteful decor that made the atmosphere feel both cozy and upscale. The menu offered a great variety of dishes, and I decided to try the [dish name] along with a [drink/dessert]. The food was absolutely delicious – well-seasoned, perfectly cooked, and beautifully presented. It’s clear that they use fresh, high-quality ingredients. The service was equally impressive. The staff were attentive, friendly, and knowledgeable about the menu. They made sure everything was to our liking without being overbearing. Overall, I highly recommend [Gulshan 2] to anyone looking for a great dining experience. I’ll definitely be returning soon! --- 42: I recently visited [Gulshan 2 ] and I must say it was a delightful experience! The ambiance was warm and inviting, with tasteful decor that made the atmosphere feel both cozy and upscale. The menu offered a great variety of dishes, and I decided to try the [dish name] along with a [drink/dessert]. The food was absolutely delicious – well-seasoned, perfectly cooked, and beautifully presented. It’s clear that they use fresh, high-quality ingredients. The service was equally impressive. The staff were attentive, friendly, and knowledgeable about the menu. They made sure everything was to our liking without being overbearing. Overall, I highly recommend [Gulshan 2] to anyone looking for a great dining experience. I’ll definitely be returning soon! --- 43: Good atmosphere for gathering, meeting , fun etc. You have plenty of choices. Different cuisines are available there. Kids zone, clean washroom, parking area, game zone . You will find all the things in one under the roof. Cheers  --- 44: Good atmosphere for gathering, meeting , fun etc. You have plenty of choices. Different cuisines are available there. Kids zone, clean washroom, parking area, game zone . You will find all the things in one under the roof. Cheers  --- 45: Went there tonight for dinner. I was craving Indian food since a few days and noticed Darbar. I took their butter chicken platter which comes with a butter naan, two pieces of reshmi kebab, dal makhani and of course butter chicken. It was 520 Tk. The presentation was nice and the food looked absolutely yummy. But I really could not differentiate between the dal makhani and butter chicken. Both tasted the same to me. And the reshmi kebab was bland. Overall, the platter was just mediocre. Then I had devilled noodles from Taste of Lanka which comes with two chicken skewers and cost 419 Tk. It was a flavorful dish and good for people who loves spicy food. Finally, I had the red velvet cheesecake ice cream from savoy. The cost per scoop was 210 Tk! It was the best. I loved the texture of the ice cream. It was rich and creamy, topped with cheesecake crumbles and had the perfect tangy flavors of red velvet cake. It felt quite refreshing after a heavy meal, and it has become my new favorite ice cream flavor. I loved the place a lot. It was spacious and well decorated. I enjoyed the ambience! Planning to go there again soon. --- 46: Went there tonight for dinner. I was craving Indian food since a few days and noticed Darbar. I took their butter chicken platter which comes with a butter naan, two pieces of reshmi kebab, dal makhani and of course butter chicken. It was 520 Tk. The presentation was nice and the food looked absolutely yummy. But I really could not differentiate between the dal makhani and butter chicken. Both tasted the same to me. And the reshmi kebab was bland. Overall, the platter was just mediocre. Then I had devilled noodles from Taste of Lanka which comes with two chicken skewers and cost 419 Tk. It was a flavorful dish and good for people who loves spicy food. Finally, I had the red velvet cheesecak

In [146]:
import torch
print(torch.__version__)

2.9.0+cu128

In [155]:
import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.preprocessing import StandardScaler
import mysql.connector

# Connect to MySQL database
db_connection = mysql.connector.connect(
    host="localhost", 
    user="mukul", 
    password="mukul1572", 
    database="feast_ai"
)

# Create a cursor object
cursor = db_connection.cursor()

# Query to fetch data from 'restaurants' table
query = "SELECT * FROM restaurants;"
df = pd.read_sql(query, db_connection)

# Initialize the pre-trained model for generating embeddings
model = SentenceTransformer('all-MiniLM-L6-v2')
scaler = StandardScaler()

# Function to generate embeddings
def create_embeddings(df):
    # Prepare text fields (name, address, sample_user_reviews)
    text_fields = df[['name', 'address', 'sample_user_reviews']].fillna('')
    text_data = text_fields.apply(lambda row: ' '.join(row), axis=1)
    
    # Generate embeddings for the text fields
    text_embeddings = model.encode(text_data.tolist())

    # Handle numerical fields (rating, reviews_count, latitude, longitude, price_per_person)
    numerical_fields = df[['rating', 'reviews_count', 'latitude', 'longitude', 'price_per_person']].fillna(0)
    numerical_embeddings = scaler.fit_transform(numerical_fields)

    # Combine both textual and numerical embeddings
    combined_embeddings = [list(text_embeddings[i]) + list(numerical_embeddings[i]) for i in range(len(df))]
    return combined_embeddings

# Generate the embeddings
embeddings = create_embeddings(df)

# Add the embeddings to the dataframe
df['embedding'] = embeddings

# Insert the embeddings into the MySQL database (as string)
for idx, row in df.iterrows():
    embedding_str = str(row['embedding'])  # Convert list to string
    cursor.execute(f"UPDATE restaurants SET embedding = %s WHERE id = %s", (embedding_str, row['id']))

# Commit the changes to the database
db_connection.commit()

# Optionally, you can print the results for verification
cursor.execute("SELECT id, name, embedding FROM restaurants LIMIT 10;")
result = cursor.fetchall()

# Print the first 10 rows to check the embeddings
for row in result:
    print(row)

# Close the cursor and connection
cursor.close()
db_connection.close()

/tmp/ipykernel_30455/579291542.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, db_connection)

(1, "Chef's Table - Gulshan 2", '[np.float32(-0.0025491077), np.float32(0.0147755975), np.float32(-0.0016787343), np.float32(0.06532087), np.float32(-0.08764511), np.float32(0.029870234), np.float32(0.011172609), np.float32(-0.09119341), np.float32(0.023560096), np.float32(-0.08019264), np.float32(0.059808943), np.float32(-0.08881376), np.float32(0.0046205865), np.float32(-0.034219455), np.float32(0.0475535), np.float32(-0.08194177), np.float32(0.16724275), np.float32(-0.040273488), np.float32(0.01808121), np.float32(-0.11387194), np.float32(-0.05904174), np.float32(-0.015615696), np.float32(0.016466457), np.float32(-0.03824349), np.float32(-0.049651373), np.float32(-0.04215001), np.float32(-0.009599975), np.float32(-0.019718083), np.float32(0.00084841374), np.float32(-0.08868401), np.float32(-0.047066297), np.float32(0.06809727), np.float32(-0.015955627), np.float32(0.063571654), np.float32(-0.0014463639), np.float32(0.007965768), np.float32(0.05522767), np.float32(-0.042088985), np.float32(0.056640822), np.float32(0.030714221), np.float32(-0.0032805281), np.float32(0.021106848), np.float32(0.05750322), np.float32(0.030286556), np.float32(0.004361589), np.float32(0.040704656), np.float32(-0.03537652), np.float32(-0.038301665), np.float32(-0.03819956), np.float32(-0.048981577), np.float32(-0.1075887), np.float32(0.058983717), np.float32(0.006880032), np.float32(-0.05308738), np.float32(0.046531647), np.float32(-0.025464348), np.float32(-0.028890511), np.float32(-0.10849365), np.float32(-0.053307366), np.float32(0.05207176), np.float32(0.023610163), np.float32(0.057167325), np.float32(-0.001089029), np.float32(0.008982479), np.float32(-0.0398504), np.float32(-0.0548134), np.float32(-0.038095865), np.float32(0.025510157), np.float32(0.048718464), np.float32(-0.015590967), np.float32(0.009792097), np.float32(-0.018004343), np.float32(0.02038553), np.float32(0.011976215), np.float32(-0.10041477), np.float32(-0.07801802), np.float32(0.036678538), np.float32(-0.07106895), np.float32(-0.069720596), np.float32(0.028991839), np.float32(-0.06932175), np.float32(0.026953842), np.float32(0.055063456), np.float32(0.0016568712), np.float32(-0.015583854), np.float32(-0.09536702), np.float32(-0.04139248), np.float32(-0.016708521), np.float32(0.02426), np.float32(-0.017509721), np.float32(0.10552402), np.float32(0.023446988), np.float32(-0.04798711), np.float32(-0.050156146), np.float32(0.0025666603), np.float32(0.03304906), np.float32(-0.015042468), np.float32(-0.07636773), np.float32(-0.013986044), np.float32(0.03606652), np.float32(-0.012744204), np.float32(0.053553402), np.float32(0.014649965), np.float32(-0.005856307), np.float32(-0.046609882), np.float32(0.016742272), np.float32(0.06159788), np.float32(0.009519386), np.float32(-0.009223407), np.float32(-0.0052101747), np.float32(-0.066227645), np.float32(0.06677091), np.float32(-0.039658196), np.float32(-0.054703943), np.float32(-0.08937448), np.float32(0.034787253), np.float32(0.045742583), np.float32(-0.027746392), np.float32(0.052576642), np.float32(-0.004850017), np.float32(0.002448031), np.float32(0.064212665), np.float32(-0.038182776), np.float32(0.033267036), np.float32(-0.12187539), np.float32(-0.04361415), np.float32(0.06417145), np.float32(3.1875186e-33), np.float32(-0.011769284), np.float32(-0.048452057), np.float32(0.06873612), np.float32(-0.010412281), np.float32(0.11705979), np.float32(-0.018838929), np.float32(-0.005474653), np.float32(-0.028215136), np.float32(0.015797868), np.float32(0.0730193), np.float32(0.027487574), np.float32(-0.07080398), np.float32(-0.027996453), np.float32(0.014297283), np.float32(0.017253382), np.float32(0.047039375), np.float32(-0.028568616), np.float32(-0.0033642645), np.float32(0.0041403812), np.float32(-0.036427677), np.float32(-0.015347332), np.float32(-0.03166219), np.float32(0.053435575), np.float32(0.02608237), np.float32(-0.055168215), np.float32(0.06766322), np.float32(0.06655943), np.float32(0.022924287), np.float32(0.019256555), np.float32(0.015342123), np.float32(-0.0021395027), np.float32(-0.0089383945), np.float32(-0.05311933), np.float32(-0.022850418), np.float32(-0.109795935), np.float32(0.005054782), np.float32(-0.0066857818), np.float32(0.024448855), np.float32(0.049396783), np.float32(-0.0068512196), np.float32(-0.053308826), np.float32(0.053891823), np.float32(-0.04843374), np.float32(0.04392815), np.float32(-0.051692314), np.float32(0.045495786), np.float32(-0.0023849627), np.float32(0.08891492), np.float32(-0.0022224626), np.float32(0.030342665), np.float32(-0.055752825), np.float32(-0.028526757), np.float32(0.0016590463), np.float32(0.09187021), np.float32(-0.022786386), np.float32(-0.06480642), np.float32(0.022045324), np.float32(0.03799945), np.float32(0.03440998), np.float32(0.010101078), np.float32(0.043111682), np.float32(0.009016968), np.float32(-0.089381404), np.float32(-0.053889796), np.float32(-0.014929129), np.float32(0.04890372), np.float32(-0.05648926), np.float32(-0.04225683), np.float32(0.085039176), np.float32(0.031929374), np.float32(-0.033852696), np.float32(0.00745649), np.float32(0.08528808), np.float32(0.035723604), np.float32(-0.0014114144), np.float32(-0.0538577), np.float32(-0.023744622), np.float32(-0.06144737), np.float32(0.04885846), np.float32(0.059516706), np.float32(0.052218486), np.float32(0.09510822), np.float32(-0.038818687), np.float32(0.012538347), np.float32(-0.1310881), np.float32(0.01667099), np.float32(0.026957538), np.float32(-0.035569012), np.float32(0.029634578), np.float32(0.06300884), np.float32(-0.07206728), np.float32(0.0148256), np.float32(0.12055869), np.float32(0.034274273), np.float32(-0.040153373), np.float32(-4.500136e-33), np.float32(0.008776425), np.float32(-0.029468944), np.float32(-0.078387804), np.float32(0.029611098), np.float32(0.020133736), np.float32(-0.057919182), np.float32(-0.057255786), np.float32(-0.049650863), np.float32(0.01150809), np.float32(0.016422732), np.float32(-0.10393005), np.float32(0.024340563), np.float32(0.013649657), np.float32(-0.0098969), np.float32(-0.0044819), np.float32(0.08414584), np.float32(0.024480382), np.float32(0.05226807), np.float32(-0.06101811), np.float32(-0.0023669126), np.float32(0.018956162), np.float32(0.12784415), np.float32(-0.016108297), np.float32(0.011704228), np.float32(-0.01790064), np.float32(0.08680087), np.float32(-0.049615216), np.float32(-0.017139785), np.float32(-0.089861184), np.float32(0.015376022), np.float32(-0.031182785), np.float32(-0.13958764), np.float32(0.011822946), np.float32(0.036089607), np.float32(-0.018279709), np.float32(0.004185453), np.float32(-0.0013992727), np.float32(0.0031566708), np.float32(-0.051468287), np.float32(0.10381835), np.float32(0.0758091), np.float32(0.0492526), np.float32(0.022537533), np.float32(0.10854492), np.float32(0.048010312), np.float32(0.057884168), np.float32(0.0057562403), np.float32(-0.09073845), np.float32(-0.020380463), np.float32(-0.11592329), np.float32(0.0049651214), np.float32(-0.053712852), np.float32(-0.07393116), np.float32(-0.066009805), np.float32(0.030304817), np.float32(0.025893522), np.float32(-0.019930953), np.float32(0.013940697), np.float32(-0.010256786), np.float32(-0.039821703), np.float32(-0.01659833), np.float32(0.098634474), np.float32(0.020704605), np.float32(0.009482135), np.float32(0.07474105), np.float32(0.027552709), np.float32(0.075084515), np.float32(-0.024863297), np.float32(0.04068047), np.float32(0.009749915), np.float32(-0.105156064), np.float32(-0.0019040615), np.float32(-0.012505076), np.float32(0.0128235845), np.float32(-0.007222387), np.float32(0.039101694), np.float32(-0.003141235), np.float32(-0.00019459901), np.float32(-0.05573564), np.float32(-0.019192152), np.float32(0.004743857), np.float32(-0.029556684), np.float32(-0.021717263), np.float32(-0.05107639), np.float32(0.037791796), np.float32(0.0493315), np.float32(-0.01519786), np.float32(0.065446086), np.float32(0.09638426), np.float32(0.1114975), np.float32(-0.063675486), np.float32(0.014336981), np.float32(-0.026077585), np.float32(0.021275856), np.float32(0.09697815), np.float32(-5.1018983e-08), np.float32(0.01836712), np.float32(-0.06867538), np.float32(-0.064799), np.float32(0.099301316), np.float32(-0.04910147), np.float32(-0.08957873), np.float32(0.02692587), np.float32(0.034899805), np.float32(0.049791697), np.float32(0.029870488), np.float32(-0.0009206858), np.float32(0.026211293), np.float32(-0.0484172), np.float32(0.025213461), np.float32(-0.0197383), np.float32(0.038218036), np.float32(0.033506148), np.float32(0.033014167), np.float32(-0.011790549), np.float32(0.007499985), np.float32(0.037313636), np.float32(0.036163073), np.float32(0.01026986), np.float32(-0.06794229), np.float32(-0.04629006), np.float32(-0.01268638), np.float32(-0.058820724), np.float32(0.032132857), np.float32(-0.046927735), np.float32(-0.013219182), np.float32(0.02707798), np.float32(-0.019143151), np.float32(0.0681352), np.float32(0.04889573), np.float32(0.08590842), np.float32(-0.001813767), np.float32(-0.071009494), np.float32(-0.04982987), np.float32(0.004430723), np.float32(-0.005840357), np.float32(-0.1374986), np.float32(-0.06332825), np.float32(-0.042360466), np.float32(0.020592676), np.float32(-0.028124787), np.float32(0.0016554324), np.float32(-0.025744319), np.float32(0.03745982), np.float32(-0.011728816), np.float32(0.06804168), np.float32(-0.051092874), np.float32(-0.059650455), np.float32(0.050512478), np.float32(0.0144176455), np.float32(-0.0044954955), np.float32(0.07046758), np.float32(-0.008267778), np.float32(-0.040622924), np.float32(0.08818728), np.float32(-0.015827607), np.float32(0.10417006), np.float32(-0.013843859), np.float32(-0.10355917), np.float32(0.005612075), np.float64(1.6145872255165037), np.float64(2.5809388737513217), np.float64(0.8094869284148134), np.float64(0.43911426435215745), np.float64(-0.011480097893679935)]')
(2, 'The New Gulshan Plaza Restaurant', '[np.float32(-0.01715566), np.float32(-0.03358817), np.float32(0.02979571), np.float32(0.038461898), np.float32(-0.06957483), np.float32(-0.0059837047), np.float32(0.044504344), np.float32(-0.080668114), np.float32(-0.035467483), np.float32(-0.06989281), np.float32(0.098840244), np.float32(-0.07808183), np.float32(0.012371554), np.float32(0.0070682275), np.float32(0.0773399), np.float32(-0.08661731), np.float32(0.19792795), np.float32(-0.06655608), np.float32(-0.052961253), np.float32(-0.12815663), np.float32(0.009489776), np.float32(-0.053136885), np.float32(0.014545744), np.float32(-0.0471515), np.float32(-0.07805704), np.float32(-0.029395217), np.float32(0.016359597), np.float32(-0.04775847), np.float32(-0.0034245753), np.float32(-0.11537437), np.float32(0.030417819), np.float32(0.074843474), np.float32(-0.028494004), np.float32(0.03239661), np.float32(0.0013109392), np.float32(0.04316908), np.float32(0.030125858), np.float32(-0.07695941), np.float32(0.09877171), np.float32(0.025074195), np.float32(0.0033362745), np.float32(0.02239617), np.float32(0.022238102), np.float32(-0.013282211), np.float32(0.007723262), np.float32(0.04007973), np.float32(-0.04015548), np.float32(-0.024042362), np.float32(-0.018779056), np.float32(-0.04100004), np.float32(-0.04213328), np.float32(0.034752406), np.float32(-0.0018927942), np.float32(0.01478725), np.float32(0.052300457), np.float32(-0.018345613), np.float32(-0.042366087), np.float32(-0.122636855), np.float32(-0.059837166), np.float32(0.022512471), np.float32(0.048327874), np.float32(0.034180872), np.float32(0.0019675666), np.float32(-0.041893046), np.float32(-0.011739893), np.float32(-0.074822165), np.float32(-0.038095374), np.float32(-0.015809279), np.float32(0.03951272), np.float32(-0.035514448), np.float32(-0.007057491), np.float32(-0.0034209567), np.float32(0.04354448), np.float32(0.027057689), np.float32(-0.110707715), np.float32(-0.08551987), np.float32(0.0025789156), np.float32(-0.06430613), np.float32(-0.0406664), np.float32(-0.00011244178), np.float32(0.009127007), np.float32(0.044862516), np.float32(0.018563185), np.float32(0.014025359), np.float32(-0.020435149), np.float32(-0.08654646), np.float32(-0.028880209), np.float32(0.026100904), np.float32(0.031486355), np.float32(-0.04197662), np.float32(0.11915662), np.float32(0.06368208), np.float32(-0.060896844), np.float32(-0.037721433), np.float32(0.081733465), np.float32(-0.0021208285), np.float32(-0.06661289), np.float32(-0.06533754), np.float32(-0.015805848), np.float32(0.040201902), np.float32(0.003116451), np.float32(0.030321872), np.float32(0.037332952), np.float32(-0.062103864), np.float32(-0.024237389), np.float32(0.0028168303), np.float32(0.022233523), np.float32(0.04460405), np.float32(-0.0047278237), np.float32(0.042172812), np.float32(-0.061337955), np.float32(0.05205657), np.float32(0.026297843), np.float32(-0.024744771), np.float32(-0.057168588), np.float32(0.04745944), np.float32(0.024804303), np.float32(-0.042005487), np.float32(-0.0336574), np.float32(-7.293793e-05), np.float32(0.05271911), np.float32(0.013780783), np.float32(0.0026760693), np.float32(0.023168365), np.float32(-0.07339132), np.float32(-0.007837638), np.float32(0.10832738), np.float32(4.819791e-33), np.float32(-0.04140661), np.float32(-0.049328547), np.float32(0.06598575), np.float32(-0.036644224), np.float32(0.082523584), np.float32(-0.06560864), np.float32(-0.03412176), np.float32(0.01207606), np.float32(0.026315773), np.float32(-0.004349855), np.float32(0.027362274), np.float32(-0.07820936), np.float32(-0.034921616), np.float32(0.0030180626), np.float32(0.027906211), np.float32(0.045636073), np.float32(-0.063652955), np.float32(-0.022842638), np.float32(0.006512449), np.float32(0.039727777), np.float32(-0.006897411), np.float32(-0.04033242), np.float32(-0.0068365117), np.float32(-0.013408073), np.float32(-0.04133866), np.float32(0.006514342), np.float32(0.021272035), np.float32(0.017648514), np.float32(0.042574897), np.float32(0.01657065), np.float32(0.017187485), np.float32(-0.03410717), np.float32(-0.06691462), np.float32(0.050901327), np.float32(-0.10030408), np.float32(-0.046930533), np.float32(-0.062222227), np.float32(0.020628447), np.float32(-0.032414015), np.float32(-0.0009507909), np.float32(-0.052766442), np.float32(0.06739408), np.float32(-0.009966289), np.float32(0.069369905), np.float32(-0.0036998023), np.float32(0.055539962), np.float32(-0.008903453), np.float32(0.057728667), np.float32(-0.024511594), np.float32(0.019163802), np.float32(-0.039751075), np.float32(-0.043617394), np.float32(-0.011216711), np.float32(0.10170591), np.float32(-0.04451809), np.float32(0.033082645), np.float32(0.05122206), np.float32(0.014020703), np.float32(0.04073373), np.float32(0.00043783267), np.float32(0.050730903), np.float32(0.0028401997), np.float32(-0.048669044), np.float32(-0.04355731), np.float32(-0.007690727), np.float32(-0.015924629), np.float32(-0.035359267), np.float32(0.002184031), np.float32(0.07556718), np.float32(0.020817235), np.float32(-0.01482372), np.float32(0.019118361), np.float32(0.020941371), np.float32(0.08493308), np.float32(-0.023601204), np.float32(-0.049090974), np.float32(-0.040590994), np.float32(-0.00010008354), np.float32(0.019113667), np.float32(0.040038764), np.float32(0.058704812), np.float32(0.063223), np.float32(-0.020693127), np.float32(-0.039247844), np.float32(-0.091699764), np.float32(0.02517364), np.float32(0.018028807), np.float32(-0.05810017), np.float32(0.047584336), np.float32(0.053198896), np.float32(-0.08269504), np.float32(0.11513581), np.float32(0.05272365), np.float32(0.0030685158), np.float32(0.0043593557), np.float32(-5.5518797e-33), np.float32(0.020691477), np.float32(0.009774472), np.float32(-0.05566721), np.float32(0.03791932), np.float32(0.014062178), np.float32(0.024163723), np.float32(-0.075201064), np.float32(-0.0132886795), np.float32(0.008851868), np.float32(0.03176319), np.float32(-0.07362084), np.float32(0.052919783), np.float32(0.02599331), np.float32(0.008636105), np.float32(0.039112993), np.float32(0.11603858), np.float32(0.06015212), np.float32(0.011698154), np.float32(-0.07737835), np.float32(-0.0008938255), np.float32(0.005817465), np.float32(0.11380471), np.float32(-0.077805795), np.float32(-0.0028211344), np.float32(-0.04131298), np.float32(0.12435206), np.float32(-0.06692779), np.float32(0.014494305), np.float32(-0.040023528), np.float32(0.0075112013), np.float32(-0.033184595), np.float32(-0.09603632), np.float32(0.007867947), np.float32(0.05543094), np.float32(0.07609736), np.float32(0.009390079), np.float32(0.016066313), np.float32(-0.02215318), np.float32(-0.06811312), np.float32(0.11999998), np.float32(0.097253464), np.float32(0.1046494), np.float32(-0.018317027), np.float32(0.104032725), np.float32(0.009233848), np.float32(0.012776567), np.float32(-0.024955735), np.float32(-0.123432025), np.float32(-0.0027228764), np.float32(-0.098300815), np.float32(0.058340274), np.float32(-0.035754934), np.float32(-0.07875054), np.float32(-0.038480863), np.float32(0.03758739), np.float32(0.03210047), np.float32(0.009050027), np.float32(-0.03146193), np.float32(0.034117114), np.float32(-0.08686485), np.float32(-0.077933535), np.float32(-0.0016342296), np.float32(-0.0008064239), np.float32(-0.00972717), np.float32(0.037200898), np.float32(-0.04799767), np.float32(0.08756186), np.float32(-0.013310555), np.float32(0.043698702), np.float32(-0.016717508), np.float32(-0.123433545), np.float32(0.014895623), np.float32(-0.01079367), np.float32(-0.031308163), np.float32(0.0115993675), np.float32(0.04274864), np.float32(-0.041534927), np.float32(0.043135367), np.float32(0.0069590085), np.float32(-0.022841996), np.float32(-0.03319569), np.float32(-0.012353416), np.float32(-0.046823803), np.float32(-0.08171087), np.float32(-0.012902127), np.float32(0.10026216), np.float32(0.01882515), np.float32(0.024918994), np.float32(0.07752737), np.float32(0.029910957), np.float32(-0.028912747), np.float32(0.04557481), np.float32(0.010454486), np.float32(0.013822987), np.float32(0.0924348), np.float32(-5.3305325e-08), np.float32(0.0807007), np.float32(-0.10688303), np.float32(-0.022362953), np.float32(0.07621128), np.float32(-0.02679825), np.float32(-0.07714853), np.float32(-0.006851405), np.float32(0.07729086), np.float32(0.04575653), np.float32(0.024128946), np.float32(-0.024401542), np.float32(0.09093255), np.float32(-0.079837084), np.float32(0.06314456), np.float32(-0.03788414), np.float32(0.0042987186), np.float32(0.03671963), np.float32(0.002603504), np.float32(-0.006090761), np.float32(-0.01058637), np.float32(0.044263452), np.float32(0.06184707), np.float32(0.014199274), np.float32(-0.029697502), np.float32(-0.04867891), np.float32(0.028430402), np.float32(-0.038506605), np.float32(-0.008079681), np.float32(-0.085743956), np.float32(0.0029283322), np.float32(0.026577948), np.float32(-0.028199371), np.float32(-0.075956576), np.float32(0.004164826), np.float32(0.064363584), np.float32(0.050122745), np.float32(-0.013177485), np.float32(-0.05396863), np.float32(0.031272117), np.float32(0.03280298), np.float32(-0.08598859), np.float32(-0.06289159), np.float32(-0.038420267), np.float32(0.024254147), np.float32(0.035780657), np.float32(-0.04249163), np.float32(0.025089901), np.float32(-0.04280552), np.float32(-0.03931057), np.float32(-0.022568231), np.float32(-0.057130285), np.float32(-0.051186584), np.float32(0.015701488), np.float32(0.024838971), np.float32(-0.009762196), np.float32(0.033142094), np.float32(-0.042179115), np.float32(-0.061619047), np.float32(0.043471437), np.float32(0.030312458), np.float32(0.090741105), np.float32(0.057442974), np.float32(-0.10018824), np.float32(0.043378547), np.float64(-0.010325848535278188), np.float64(0.707253595136279), np.float64(0.744643768080152), np.float64(0.41790383650713664), np.float64(-0.8267436652356226)]')

In [156]:
import mysql.connector

# Reconnect to the MySQL database
db_connection = mysql.connector.connect(
    host="localhost", 
    user="mukul", 
    password="mukul1572", 
    database="feast_ai"
)

# Create a cursor object
cursor = db_connection.cursor()

# Fetch the first 10 rows from the restaurants table
cursor.execute("SELECT id, name, embedding FROM restaurants LIMIT 10;")
result = cursor.fetchall()

# Print the results to verify embeddings
for row in result:
    restaurant_id, name, embedding = row
    print(f"Restaurant ID: {restaurant_id}, Name: {name}")
    print(f"Embedding: {embedding[:100]}...")  # Print first 100 characters of embedding
    print()

# Close the cursor and connection
cursor.close()
db_connection.close()

Restaurant ID: 1, Name: Chef's Table - Gulshan 2
Embedding: [np.float32(-0.0025491077), np.float32(0.0147755975), np.float32(-0.0016787343), np.float32(0.065320...

Restaurant ID: 2, Name: The New Gulshan Plaza Restaurant
Embedding: [np.float32(-0.01715566), np.float32(-0.03358817), np.float32(0.02979571), np.float32(0.038461898), ...

Restaurant ID: 3, Name: Seasonal Tastes
Embedding: [np.float32(0.03963703), np.float32(0.002772861), np.float32(0.036883738), np.float32(0.105645314), ...

Restaurant ID: 4, Name: Sultan's Dine Gulshan Branch
Embedding: [np.float32(0.02056612), np.float32(-0.043605354), np.float32(-0.008212057), np.float32(0.039003976)...

Restaurant ID: 5, Name: HEXA Dine - Restaurant & Café
Embedding: [np.float32(0.016291564), np.float32(0.0022224374), np.float32(0.038305666), np.float32(0.09409222),...

Restaurant ID: 6, Name: The Garden Kitchen at Sheraton Dhaka
Embedding: [np.float32(0.041800834), np.float32(0.012373875), np.float32(-0.018197004), np.float32(0.04602572),...

Restaurant ID: 7, Name: Lounge Comida
Embedding: [np.float32(0.05992418), np.float32(0.004749437), np.float32(-0.014104506), np.float32(0.052861236),...

Restaurant ID: 8, Name: Galito's Gulshan-2
Embedding: [np.float32(-0.023049247), np.float32(-0.07287255), np.float32(-0.007143477), np.float32(0.069911875...

Restaurant ID: 9, Name: Garlic 'n Ginger Gulshan
Embedding: [np.float32(-0.06726046), np.float32(0.016322214), np.float32(0.009865021), np.float32(0.08833715), ...

Restaurant ID: 10, Name: Handi (Gulshan Branch)
Embedding: [np.float32(0.0054504406), np.float32(0.014998055), np.float32(-0.035818886), np.float32(0.019684438...

In [159]:
# Check the raw embedding string for each restaurant
for row in result:
    embedding_str = row[2]  # Assuming embedding is in the 3rd column
    print(f"Raw embedding for Restaurant ID {row[0]}: {embedding_str}")

Raw embedding for Restaurant ID 1: [np.float32(-0.0025491077), np.float32(0.0147755975), np.float32(-0.0016787343), np.float32(0.06532087), np.float32(-0.08764511), np.float32(0.029870234), np.float32(0.011172609), np.float32(-0.09119341), np.float32(0.023560096), np.float32(-0.08019264), np.float32(0.059808943), np.float32(-0.08881376), np.float32(0.0046205865), np.float32(-0.034219455), np.float32(0.0475535), np.float32(-0.08194177), np.float32(0.16724275), np.float32(-0.040273488), np.float32(0.01808121), np.float32(-0.11387194), np.float32(-0.05904174), np.float32(-0.015615696), np.float32(0.016466457), np.float32(-0.03824349), np.float32(-0.049651373), np.float32(-0.04215001), np.float32(-0.009599975), np.float32(-0.019718083), np.float32(0.00084841374), np.float32(-0.08868401), np.float32(-0.047066297), np.float32(0.06809727), np.float32(-0.015955627), np.float32(0.063571654), np.float32(-0.0014463639), np.float32(0.007965768), np.float32(0.05522767), np.float32(-0.042088985), np.float32(0.056640822), np.float32(0.030714221), np.float32(-0.0032805281), np.float32(0.021106848), np.float32(0.05750322), np.float32(0.030286556), np.float32(0.004361589), np.float32(0.040704656), np.float32(-0.03537652), np.float32(-0.038301665), np.float32(-0.03819956), np.float32(-0.048981577), np.float32(-0.1075887), np.float32(0.058983717), np.float32(0.006880032), np.float32(-0.05308738), np.float32(0.046531647), np.float32(-0.025464348), np.float32(-0.028890511), np.float32(-0.10849365), np.float32(-0.053307366), np.float32(0.05207176), np.float32(0.023610163), np.float32(0.057167325), np.float32(-0.001089029), np.float32(0.008982479), np.float32(-0.0398504), np.float32(-0.0548134), np.float32(-0.038095865), np.float32(0.025510157), np.float32(0.048718464), np.float32(-0.015590967), np.float32(0.009792097), np.float32(-0.018004343), np.float32(0.02038553), np.float32(0.011976215), np.float32(-0.10041477), np.float32(-0.07801802), np.float32(0.036678538), np.float32(-0.07106895), np.float32(-0.069720596), np.float32(0.028991839), np.float32(-0.06932175), np.float32(0.026953842), np.float32(0.055063456), np.float32(0.0016568712), np.float32(-0.015583854), np.float32(-0.09536702), np.float32(-0.04139248), np.float32(-0.016708521), np.float32(0.02426), np.float32(-0.017509721), np.float32(0.10552402), np.float32(0.023446988), np.float32(-0.04798711), np.float32(-0.050156146), np.float32(0.0025666603), np.float32(0.03304906), np.float32(-0.015042468), np.float32(-0.07636773), np.float32(-0.013986044), np.float32(0.03606652), np.float32(-0.012744204), np.float32(0.053553402), np.float32(0.014649965), np.float32(-0.005856307), np.float32(-0.046609882), np.float32(0.016742272), np.float32(0.06159788), np.float32(0.009519386), np.float32(-0.009223407), np.float32(-0.0052101747), np.float32(-0.066227645), np.float32(0.06677091), np.float32(-0.039658196), np.float32(-0.054703943), np.float32(-0.08937448), np.float32(0.034787253), np.float32(0.045742583), np.float32(-0.027746392), np.float32(0.052576642), np.float32(-0.004850017), np.float32(0.002448031), np.float32(0.064212665), np.float32(-0.038182776), np.float32(0.033267036), np.float32(-0.12187539), np.float32(-0.04361415), np.float32(0.06417145), np.float32(3.1875186e-33), np.float32(-0.011769284), np.float32(-0.048452057), np.float32(0.06873612), np.float32(-0.010412281), np.float32(0.11705979), np.float32(-0.018838929), np.float32(-0.005474653), np.float32(-0.028215136), np.float32(0.015797868), np.float32(0.0730193), np.float32(0.027487574), np.float32(-0.07080398), np.float32(-0.027996453), np.float32(0.014297283), np.float32(0.017253382), np.float32(0.047039375), np.float32(-0.028568616), np.float32(-0.0033642645), np.float32(0.0041403812), np.float32(-0.036427677), np.float32(-0.015347332), np.float32(-0.03166219), np.float32(0.053435575), np.float32(0.02608237), np.float32(-0.055168215), np.float32(0.06766322), np.float32(0.06655943), np.float32(0.022924287), np.float32(0.019256555), np.float32(0.015342123), np.float32(-0.0021395027), np.float32(-0.0089383945), np.float32(-0.05311933), np.float32(-0.022850418), np.float32(-0.109795935), np.float32(0.005054782), np.float32(-0.0066857818), np.float32(0.024448855), np.float32(0.049396783), np.float32(-0.0068512196), np.float32(-0.053308826), np.float32(0.053891823), np.float32(-0.04843374), np.float32(0.04392815), np.float32(-0.051692314), np.float32(0.045495786), np.float32(-0.0023849627), np.float32(0.08891492), np.float32(-0.0022224626), np.float32(0.030342665), np.float32(-0.055752825), np.float32(-0.028526757), np.float32(0.0016590463), np.float32(0.09187021), np.float32(-0.022786386), np.float32(-0.06480642), np.float32(0.022045324), np.float32(0.03799945), np.float32(0.03440998), np.float32(0.010101078), np.float32(0.043111682), np.float32(0.009016968), np.float32(-0.089381404), np.float32(-0.053889796), np.float32(-0.014929129), np.float32(0.04890372), np.float32(-0.05648926), np.float32(-0.04225683), np.float32(0.085039176), np.float32(0.031929374), np.float32(-0.033852696), np.float32(0.00745649), np.float32(0.08528808), np.float32(0.035723604), np.float32(-0.0014114144), np.float32(-0.0538577), np.float32(-0.023744622), np.float32(-0.06144737), np.float32(0.04885846), np.float32(0.059516706), np.float32(0.052218486), np.float32(0.09510822), np.float32(-0.038818687), np.float32(0.012538347), np.float32(-0.1310881), np.float32(0.01667099), np.float32(0.026957538), np.float32(-0.035569012), np.float32(0.029634578), np.float32(0.06300884), np.float32(-0.07206728), np.float32(0.0148256), np.float32(0.12055869), np.float32(0.034274273), np.float32(-0.040153373), np.float32(-4.500136e-33), np.float32(0.008776425), np.float32(-0.029468944), np.float32(-0.078387804), np.float32(0.029611098), np.float32(0.020133736), np.float32(-0.057919182), np.float32(-0.057255786), np.float32(-0.049650863), np.float32(0.01150809), np.float32(0.016422732), np.float32(-0.10393005), np.float32(0.024340563), np.float32(0.013649657), np.float32(-0.0098969), np.float32(-0.0044819), np.float32(0.08414584), np.float32(0.024480382), np.float32(0.05226807), np.float32(-0.06101811), np.float32(-0.0023669126), np.float32(0.018956162), np.float32(0.12784415), np.float32(-0.016108297), np.float32(0.011704228), np.float32(-0.01790064), np.float32(0.08680087), np.float32(-0.049615216), np.float32(-0.017139785), np.float32(-0.089861184), np.float32(0.015376022), np.float32(-0.031182785), np.float32(-0.13958764), np.float32(0.011822946), np.float32(0.036089607), np.float32(-0.018279709), np.float32(0.004185453), np.float32(-0.0013992727), np.float32(0.0031566708), np.float32(-0.051468287), np.float32(0.10381835), np.float32(0.0758091), np.float32(0.0492526), np.float32(0.022537533), np.float32(0.10854492), np.float32(0.048010312), np.float32(0.057884168), np.float32(0.0057562403), np.float32(-0.09073845), np.float32(-0.020380463), np.float32(-0.11592329), np.float32(0.0049651214), np.float32(-0.053712852), np.float32(-0.07393116), np.float32(-0.066009805), np.float32(0.030304817), np.float32(0.025893522), np.float32(-0.019930953), np.float32(0.013940697), np.float32(-0.010256786), np.float32(-0.039821703), np.float32(-0.01659833), np.float32(0.098634474), np.float32(0.020704605), np.float32(0.009482135), np.float32(0.07474105), np.float32(0.027552709), np.float32(0.075084515), np.float32(-0.024863297), np.float32(0.04068047), np.float32(0.009749915), np.float32(-0.105156064), np.float32(-0.0019040615), np.float32(-0.012505076), np.float32(0.0128235845), np.float32(-0.007222387), np.float32(0.039101694), np.float32(-0.003141235), np.float32(-0.00019459901), np.float32(-0.05573564), np.float32(-0.019192152), np.float32(0.004743857), np.float32(-0.029556684), np.float32(-0.021717263), np.float32(-0.05107639), np.float32(0.037791796), np.float32(0.0493315), np.float32(-0.01519786), np.float32(0.065446086), np.float32(0.09638426), np.float32(0.1114975), np.float32(-0.063675486), np.float32(0.014336981), np.float32(-0.026077585), np.float32(0.021275856), np.float32(0.09697815), np.float32(-5.1018983e-08), np.float32(0.01836712), np.float32(-0.06867538), np.float32(-0.064799), np.float32(0.099301316), np.float32(-0.04910147), np.float32(-0.08957873), np.float32(0.02692587), np.float32(0.034899805), np.float32(0.049791697), np.float32(0.029870488), np.float32(-0.0009206858), np.float32(0.026211293), np.float32(-0.0484172), np.float32(0.025213461), np.float32(-0.0197383), np.float32(0.038218036), np.float32(0.033506148), np.float32(0.033014167), np.float32(-0.011790549), np.float32(0.007499985), np.float32(0.037313636), np.float32(0.036163073), np.float32(0.01026986), np.float32(-0.06794229), np.float32(-0.04629006), np.float32(-0.01268638), np.float32(-0.058820724), np.float32(0.032132857), np.float32(-0.046927735), np.float32(-0.013219182), np.float32(0.02707798), np.float32(-0.019143151), np.float32(0.0681352), np.float32(0.04889573), np.float32(0.08590842), np.float32(-0.001813767), np.float32(-0.071009494), np.float32(-0.04982987), np.float32(0.004430723), np.float32(-0.005840357), np.float32(-0.1374986), np.float32(-0.06332825), np.float32(-0.042360466), np.float32(0.020592676), np.float32(-0.028124787), np.float32(0.0016554324), np.float32(-0.025744319), np.float32(0.03745982), np.float32(-0.011728816), np.float32(0.06804168), np.float32(-0.051092874), np.float32(-0.059650455), np.float32(0.050512478), np.float32(0.0144176455), np.float32(-0.0044954955), np.float32(0.07046758), np.float32(-0.008267778), np.float32(-0.040622924), np.float32(0.08818728), np.float32(-0.015827607), np.float32(0.10417006), np.float32(-0.013843859), np.float32(-0.10355917), np.float32(0.005612075), np.float64(1.6145872255165037), np.float64(2.5809388737513217), np.float64(0.8094869284148134), np.float64(0.43911426435215745), np.float64(-0.011480097893679935)]
Raw embedding for Restaurant ID 2: [np.float32(-0.01715566), np.float32(-0.03358817), np.float32(0.02979571), np.float32(0.038461898), np.float32(-0.06957483), np.float32(-0.0059837047), np.float32(0.044504344), np.float32(-0.080668114), np.float32(-0.035467483), np.float32(-0.06989281), np.float32(0.098840244), np.float32(-0.07808183), np.float32(0.012371554), np.float32(0.0070682275), np.float32(0.0773399), np.float32(-0.08661731), np.float32(0.19792795), np.float32(-0.06655608), np.float32(-0.052961253), np.float32(-0.12815663), np.float32(0.009489776), np.float32(-0.053136885), np.float32(0.014545744), np.float32(-0.0471515), np.float32(-0.07805704), np.float32(-0.029395217), np.float32(0.016359597), np.float32(-0.04775847), np.float32(-0.0034245753), np.float32(-0.11537437), np.float32(0.030417819), np.float32(0.074843474), np.float32(-0.028494004), np.float32(0.03239661), np.float32(0.0013109392), np.float32(0.04316908), np.float32(0.030125858), np.float32(-0.07695941), np.float32(0.09877171), np.float32(0.025074195), np.float32(0.0033362745), np.float32(0.02239617), np.float32(0.022238102), np.float32(-0.013282211), np.float32(0.007723262), np.float32(0.04007973), np.float32(-0.04015548), np.float32(-0.024042362), np.float32(-0.018779056), np.float32(-0.04100004), np.float32(-0.04213328), np.float32(0.034752406), np.float32(-0.0018927942), np.float32(0.01478725), np.float32(0.052300457), np.float32(-0.018345613), np.float32(-0.042366087), np.float32(-0.122636855), np.float32(-0.059837166), np.float32(0.022512471), np.float32(0.048327874), np.float32(0.034180872), np.float32(0.0019675666), np.float32(-0.041893046), np.float32(-0.011739893), np.float32(-0.074822165), np.float32(-0.038095374), np.float32(-0.015809279), np.float32(0.03951272), np.float32(-0.035514448), np.float32(-0.007057491), np.float32(-0.0034209567), np.float32(0.04354448), np.float32(0.027057689), np.float32(-0.110707715), np.float32(-0.08551987), np.float32(0.0025789156), np.float32(-0.06430613), np.float32(-0.0406664), np.float32(-0.00011244178), np.float32(0.009127007), np.float32(0.044862516), np.float32(0.018563185), np.float32(0.014025359), np.float32(-0.020435149), np.float32(-0.08654646), np.float32(-0.028880209), np.float32(0.026100904), np.float32(0.031486355), np.float32(-0.04197662), np.float32(0.11915662), np.float32(0.06368208), np.float32(-0.060896844), np.float32(-0.037721433), np.float32(0.081733465), np.float32(-0.0021208285), np.float32(-0.06661289), np.float32(-0.06533754), np.float32(-0.015805848), np.float32(0.040201902), np.float32(0.003116451), np.float32(0.030321872), np.float32(0.037332952), np.float32(-0.062103864), np.float32(-0.024237389), np.float32(0.0028168303), np.float32(0.022233523), np.float32(0.04460405), np.float32(-0.0047278237), np.float32(0.042172812), np.float32(-0.061337955), np.float32(0.05205657), np.float32(0.026297843), np.float32(-0.024744771), np.float32(-0.057168588), np.float32(0.04745944), np.float32(0.024804303), np.float32(-0.042005487), np.float32(-0.0336574), np.float32(-7.293793e-05), np.float32(0.05271911), np.float32(0.013780783), np.float32(0.0026760693), np.float32(0.023168365), np.float32(-0.07339132), np.float32(-0.007837638), np.float32(0.10832738), np.float32(4.819791e-33), np.float32(-0.04140661), np.float32(-0.049328547), np.float32(0.06598575), np.float32(-0.036644224), np.float32(0.082523584), np.float32(-0.06560864), np.float32(-0.03412176), np.float32(0.01207606), np.float32(0.026315773), np.float32(-0.004349855), np.float32(0.027362274), np.float32(-0.07820936), np.float32(-0.034921616), np.float32(0.0030180626), np.float32(0.027906211), np.float32(0.045636073), np.float32(-0.063652955), np.float32(-0.022842638), np.float32(0.006512449), np.float32(0.039727777), np.float32(-0.006897411), np.float32(-0.04033242), np.float32(-0.0068365117), np.float32(-0.013408073), np.float32(-0.04133866), np.float32(0.006514342), np.float32(0.021272035), np.float32(0.017648514), np.float32(0.042574897), np.float32(0.01657065), np.float32(0.017187485), np.float32(-0.03410717), np.float32(-0.06691462), np.float32(0.050901327), np.float32(-0.10030408), np.float32(-0.046930533), np.float32(-0.062222227), np.float32(0.020628447), np.float32(-0.032414015), np.float32(-0.0009507909), np.float32(-0.052766442), np.float32(0.06739408), np.float32(-0.009966289), np.float32(0.069369905), np.float32(-0.0036998023), np.float32(0.055539962), np.float32(-0.008903453), np.float32(0.057728667), np.float32(-0.024511594), np.float32(0.019163802), np.float32(-0.039751075), np.float32(-0.043617394), np.float32(-0.011216711), np.float32(0.10170591), np.float32(-0.04451809), np.float32(0.033082645), np.float32(0.05122206), np.float32(0.014020703), np.float32(0.04073373), np.float32(0.00043783267), np.float32(0.050730903), np.float32(0.0028401997), np.float32(-0.048669044), np.float32(-0.04355731), np.float32(-0.007690727), np.float32(-0.015924629), np.float32(-0.035359267), np.float32(0.002184031), np.float32(0.07556718), np.float32(0.020817235), np.float32(-0.01482372), np.float32(0.019118361), np.float32(0.020941371), np.float32(0.08493308), np.float32(-0.023601204), np.float32(-0.049090974), np.float32(-0.040590994), np.float32(-0.00010008354), np.float32(0.019113667), np.float32(0.040038764), np.float32(0.058704812), np.float32(0.063223), np.float32(-0.020693127), np.float32(-0.039247844), np.float32(-0.091699764), np.float32(0.02517364), np.float32(0.018028807), np.float32(-0.05810017), np.float32(0.047584336), np.float32(0.053198896), np.float32(-0.08269504), np.float32(0.11513581), np.float32(0.05272365), np.float32(0.0030685158), np.float32(0.0043593557), np.float32(-5.5518797e-33), np.float32(0.020691477), np.float32(0.009774472), np.float32(-0.05566721), np.float32(0.03791932), np.float32(0.014062178), np.float32(0.024163723), np.float32(-0.075201064), np.float32(-0.0132886795), np.float32(0.008851868), np.float32(0.03176319), np.float32(-0.07362084), np.float32(0.052919783), np.float32(0.02599331), np.float32(0.008636105), np.float32(0.039112993), np.float32(0.11603858), np.float32(0.06015212), np.float32(0.011698154), np.float32(-0.07737835), np.float32(-0.0008938255), np.float32(0.005817465), np.float32(0.11380471), np.float32(-0.077805795), np.float32(-0.0028211344), np.float32(-0.04131298), np.float32(0.12435206), np.float32(-0.06692779), np.float32(0.014494305), np.float32(-0.040023528), np.float32(0.0075112013), np.float32(-0.033184595), np.float32(-0.09603632), np.float32(0.007867947), np.float32(0.05543094), np.float32(0.07609736), np.float32(0.009390079), np.float32(0.016066313), np.float32(-0.02215318), np.float32(-0.06811312), np.float32(0.11999998), np.float32(0.097253464), np.float32(0.1046494), np.float32(-0.018317027), np.float32(0.104032725), np.float32(0.009233848), np.float32(0.012776567), np.float32(-0.024955735), np.float32(-0.123432025), np.float32(-0.0027228764), np.float32(-0.098300815), np.float32(0.058340274), np.float32(-0.035754934), np.float32(-0.07875054), np.float32(-0.038480863), np.float32(0.03758739), np.float32(0.03210047), np.float32(0.009050027), np.float32(-0.03146193), np.float32(0.034117114), np.float32(-0.08686485), np.float32(-0.077933535), np.float32(-0.0016342296), np.float32(-0.0008064239), np.float32(-0.00972717), np.float32(0.037200898), np.float32(-0.04799767), np.float32(0.08756186), np.float32(-0.013310555), np.float32(0.043698702), np.float32(-0.016717508), np.float32(-0.123433545), np.float32(0.014895623), np.float32(-0.01079367), np.float32(-0.031308163), np.float32(0.0115993675), np.float32(0.04274864), np.float32(-0.041534927), np.float32(0.043135367), np.float32(0.0069590085), np.float32(-0.022841996), np.float32(-0.03319569), np.float32(-0.012353416), np.float32(-0.046823803), np.float32(-0.08171087), np.float32(-0.012902127), np.float32(0.10026216), np.float32(0.01882515), np.float32(0.024918994), np.float32(0.07752737), np.float32(0.029910957), np.float32(-0.028912747), np.float32(0.04557481), np.float32(0.010454486), np.float32(0.013822987), np.float32(0.0924348), np.float32(-5.3305325e-08), np.float32(0.0807007), np.float32(-0.10688303), np.float32(-0.022362953), np.float32(0.07621128), np.float32(-0.02679825), np.float32(-0.07714853), np.float32(-0.006851405), np.float32(0.07729086), np.float32(0.04575653), np.float32(0.024128946), np.float32(-0.024401542), np.float32(0.09093255), np.float32(-0.079837084), np.float32(0.06314456), np.float32(-0.03788414), np.float32(0.0042987186), np.float32(0.03671963), np.float32(0.002603504), np.float32(-0.006090761), np.float32(-0.01058637), np.float32(0.044263452), np.float32(0.06184707), np.float32(0.014199274), np.float32(-0.029697502), np.float32(-0.04867891), np.float32(0.028430402), np.float32(-0.038506605), np.float32(-0.008079681), np.float32(-0.085743956), np.float32(0.0029283322), np.float32(0.026577948), np.float32(-0.028199371), np.float32(-0.075956576), np.float32(0.004164826), np.float32(0.064363584), np.float32(0.050122745), np.float32(-0.013177485), np.float32(-0.05396863), np.float32(0.031272117), np.float32(0.03280298), np.float32(-0.08598859), np.float32(-0.06289159), np.float32(-0.038420267), np.float32(0.024254147), np.float32(0.035780657), np.float32(-0.04249163), np.float32(0.025089901), np.float32(-0.04280552), np.float32(-0.03931057), np.float32(-0.022568231), np.float32(-0.057130285), np.float32(-0.051186584), np.float32(0.015701488), np.float32(0.024838971), np.float32(-0.009762196), np.float32(0.033142094), np.float32(-0.042179115), np.float32(-0.061619047), np.float32(0.043471437), np.float32(0.030312458), np.float32(0.090741105), np.float32(0.057442974), np.float32(-0.10018824), np.float32(0.043378547), np.float64(-0.010325848535278188), np.float64(0.707253595136279), np.float64(0.744643768080152), np.float64(0.41790383650713664), np.float64(-0.8267436652356226)]